In [1]:
import sys
import pandas as pd
import numpy as np

print("python:", sys.executable)
print("pandas:", pd.__version__)
print("NumPy:", np.__version__)

python: /home/Student/career-intelligence/.venv/bin/python
pandas: 2.3.3
NumPy: 2.2.6

In [2]:
from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path.cwd().parent


ONET_DIR = PROJECT_ROOT / "data" / "raw" / "onet" / "db_31_0_csv"

print("Project root:", PROJECT_ROOT)
print("O*NET directory:", ONET_DIR)
print("Directory exists:", ONET_DIR.exists())

csv_files = sorted(ONET_DIR.glob("*.csv"))

print(f"\nNumber of CSV files found: {len(csv_files)}")

for file in csv_files:
    print(file.name)

Project root: /home/Student/career-intelligence
O*NET directory: /home/Student/career-intelligence/data/raw/onet/db_31_0_csv
Directory exists: True

Number of CSV files found: 45
abilities.csv
abilities_to_work_activities.csv
abilities_to_work_context.csv
career_interest_type_keywords.csv
career_interest_types.csv
content_model_reference.csv
education.csv
education_categories.csv
emerging_tasks.csv
essential_skills.csv
essential_skills_to_work_activities.csv
essential_skills_to_work_context.csv
gwas_to_iwas.csv
gwas_to_iwas_to_dwas.csv
interests_illustrative_activities.csv
interests_illustrative_occupations.csv
job_titles.csv
job_zone_reference.csv
job_zones.csv
knowledge.csv
level_scale_anchors.csv
occupation_data.csv
occupation_level_metadata.csv
related_occupations.csv
sample_of_reported_titles.csv
scales_reference.csv
software_skills.csv
specific_interest_areas.csv
specific_interest_areas_to_career_interest_types.csv
survey_booklet_locations.csv
task_categories.csv
task_ratings.csv
task_statements.csv
tasks_to_dwas.csv
training_and_experience.csv
training_and_experience_categories.csv
transferable_skills.csv
transferable_skills_to_work_activities.csv
transferable_skills_to_work_context.csv
work_activities.csv
work_context.csv
work_context_categories.csv
work_styles.csv
work_styles_to_work_activities.csv
work_styles_to_work_context.csv

In [3]:
import pandas as pd
from pathlib import Path

onet_dir = Path("/home/Student/career-intelligence/data/raw/onet/db_31_0_csv")

profile = []

for file in sorted(onet_dir.glob("*.csv")):
    try:
        df = pd.read_csv(file)

        profile.append({
            "file": file.name,
            "rows": len(df),
            "columns": len(df.columns),
            "column_names": ", ".join(df.columns)
        })

    except Exception as e:
        profile.append({
            "file": file.name,
            "rows": "ERROR",
            "columns": "ERROR",
            "column_names": str(e)
        })

profile_df = pd.DataFrame(profile)

profile_df

,file,rows,columns,column_names
0,abilities.csv,94640,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
1,abilities_to_work_activities.csv,381,4,"Abilities Element ID, Abilities Element Name, ..."
2,abilities_to_work_context.csv,139,4,"Abilities Element ID, Abilities Element Name, ..."
3,career_interest_type_keywords.csv,75,4,"Element ID, Element Name, Keyword, Keyword Type"
4,career_interest_types.csv,8307,9,"O*NET-SOC Code, Title, Element ID, Element Nam..."
5,content_model_reference.csv,3006,3,"Element ID, Element Name, Description"
6,education.csv,11495,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
7,education_categories.csv,24,6,"Element ID, Element Name, Scale ID, Scale Name..."
8,emerging_tasks.csv,338,8,"O*NET-SOC Code, Title, Task, Category, Origina..."
9,essential_skills.csv,18200,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
10,essential_skills_to_work_activities.csv,110,4,"Essential Skills Element ID, Essential Skills ..."
11,essential_skills_to_work_context.csv,39,4,"Essential Skills Element ID, Essential Skills ..."
12,gwas_to_iwas.csv,332,4,"GWA Element ID, GWA Element Name, IWA Element ..."
13,gwas_to_iwas_to_dwas.csv,2087,6,"GWA Element ID, GWA Element Name, IWA Element ..."
14,interests_illustrative_activities.csv,188,4,"Element ID, Element Name, Interest Type, Activity"
15,interests_illustrative_occupations.csv,186,5,"Element ID, Element Name, Interest Type, O*NET..."
16,job_titles.csv,54269,5,"O*NET-SOC Code, Title, Job Title, Short Title,..."
17,job_zone_reference.csv,4,7,"Job Zone, Name, Experience, Education, Job Tra..."
18,job_zones.csv,923,5,"O*NET-SOC Code, Title, Job Zone, Date, Domain ..."
19,knowledge.csv,60060,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
20,level_scale_anchors.csv,483,6,"Element ID, Element Name, Scale ID, Scale Name..."
21,occupation_data.csv,1016,3,"O*NET-SOC Code, Title, Description"
22,occupation_level_metadata.csv,32280,7,"O*NET-SOC Code, Title, Item, Response, N, Perc..."
23,related_occupations.csv,18460,6,"O*NET-SOC Code, Title, Related O*NET-SOC Code,..."
24,sample_of_reported_titles.csv,8189,4,"O*NET-SOC Code, Title, Reported Job Title, Sho..."
25,scales_reference.csv,33,4,"Scale ID, Scale Name, Minimum, Maximum"
26,software_skills.csv,31821,7,"O*NET-SOC Code, Title, Workplace Example, Elem..."
27,specific_interest_areas.csv,73062,9,"O*NET-SOC Code, Title, Element ID, Element Nam..."
28,specific_interest_areas_to_career_interest_typ...,53,4,"Specific Interest Areas Element ID, Specific I..."
29,survey_booklet_locations.csv,211,5,"Element ID, Element Name, Survey Item Number, ..."
30,task_categories.csv,7,4,"Scale ID, Scale Name, Category, Category Descr..."
31,task_ratings.csv,165780,15,"O*NET-SOC Code, Title, Task ID, Task, Scale ID..."
32,task_statements.csv,18838,8,"O*NET-SOC Code, Title, Task ID, Task, Task Typ..."
33,tasks_to_dwas.csv,24087,8,"O*NET-SOC Code, Title, Task ID, Task, DWA Elem..."
34,training_and_experience.csv,26812,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
35,training_and_experience_categories.csv,29,6,"Element ID, Element Name, Scale ID, Scale Name..."
36,transferable_skills.csv,45500,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
37,transferable_skills_to_work_activities.csv,122,4,"Transferable Skills Element ID, Transferable S..."
38,transferable_skills_to_work_context.csv,57,4,"Transferable Skills Element ID, Transferable S..."
39,work_activities.csv,74702,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
40,work_context.csv,305389,16,"O*NET-SOC Code, Title, Element ID, Element Nam..."
41,work_context_categories.csv,281,6,"Element ID, Element Name, Scale ID, Scale Name..."
42,work_styles.csv,37422,9,"O*NET-SOC Code, Title, Element ID, Element Nam..."
43,work_styles_to_work_activities.csv,303,4,"Work Styles Element ID, Work Styles Element Na..."
44,work_styles_to_work_context.csv,266,4,"Work Styles Element ID, Work Styles Element Na..."

In [4]:
profile_df.to_csv(
    "/home/Student/career-intelligence/data/raw/onet/onet_profile.csv",
    index=False
)

profile_df

,file,rows,columns,column_names
0,abilities.csv,94640,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
1,abilities_to_work_activities.csv,381,4,"Abilities Element ID, Abilities Element Name, ..."
2,abilities_to_work_context.csv,139,4,"Abilities Element ID, Abilities Element Name, ..."
3,career_interest_type_keywords.csv,75,4,"Element ID, Element Name, Keyword, Keyword Type"
4,career_interest_types.csv,8307,9,"O*NET-SOC Code, Title, Element ID, Element Nam..."
5,content_model_reference.csv,3006,3,"Element ID, Element Name, Description"
6,education.csv,11495,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
7,education_categories.csv,24,6,"Element ID, Element Name, Scale ID, Scale Name..."
8,emerging_tasks.csv,338,8,"O*NET-SOC Code, Title, Task, Category, Origina..."
9,essential_skills.csv,18200,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
10,essential_skills_to_work_activities.csv,110,4,"Essential Skills Element ID, Essential Skills ..."
11,essential_skills_to_work_context.csv,39,4,"Essential Skills Element ID, Essential Skills ..."
12,gwas_to_iwas.csv,332,4,"GWA Element ID, GWA Element Name, IWA Element ..."
13,gwas_to_iwas_to_dwas.csv,2087,6,"GWA Element ID, GWA Element Name, IWA Element ..."
14,interests_illustrative_activities.csv,188,4,"Element ID, Element Name, Interest Type, Activity"
15,interests_illustrative_occupations.csv,186,5,"Element ID, Element Name, Interest Type, O*NET..."
16,job_titles.csv,54269,5,"O*NET-SOC Code, Title, Job Title, Short Title,..."
17,job_zone_reference.csv,4,7,"Job Zone, Name, Experience, Education, Job Tra..."
18,job_zones.csv,923,5,"O*NET-SOC Code, Title, Job Zone, Date, Domain ..."
19,knowledge.csv,60060,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
20,level_scale_anchors.csv,483,6,"Element ID, Element Name, Scale ID, Scale Name..."
21,occupation_data.csv,1016,3,"O*NET-SOC Code, Title, Description"
22,occupation_level_metadata.csv,32280,7,"O*NET-SOC Code, Title, Item, Response, N, Perc..."
23,related_occupations.csv,18460,6,"O*NET-SOC Code, Title, Related O*NET-SOC Code,..."
24,sample_of_reported_titles.csv,8189,4,"O*NET-SOC Code, Title, Reported Job Title, Sho..."
25,scales_reference.csv,33,4,"Scale ID, Scale Name, Minimum, Maximum"
26,software_skills.csv,31821,7,"O*NET-SOC Code, Title, Workplace Example, Elem..."
27,specific_interest_areas.csv,73062,9,"O*NET-SOC Code, Title, Element ID, Element Nam..."
28,specific_interest_areas_to_career_interest_typ...,53,4,"Specific Interest Areas Element ID, Specific I..."
29,survey_booklet_locations.csv,211,5,"Element ID, Element Name, Survey Item Number, ..."
30,task_categories.csv,7,4,"Scale ID, Scale Name, Category, Category Descr..."
31,task_ratings.csv,165780,15,"O*NET-SOC Code, Title, Task ID, Task, Scale ID..."
32,task_statements.csv,18838,8,"O*NET-SOC Code, Title, Task ID, Task, Task Typ..."
33,tasks_to_dwas.csv,24087,8,"O*NET-SOC Code, Title, Task ID, Task, DWA Elem..."
34,training_and_experience.csv,26812,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
35,training_and_experience_categories.csv,29,6,"Element ID, Element Name, Scale ID, Scale Name..."
36,transferable_skills.csv,45500,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
37,transferable_skills_to_work_activities.csv,122,4,"Transferable Skills Element ID, Transferable S..."
38,transferable_skills_to_work_context.csv,57,4,"Transferable Skills Element ID, Transferable S..."
39,work_activities.csv,74702,15,"O*NET-SOC Code, Title, Element ID, Element Nam..."
40,work_context.csv,305389,16,"O*NET-SOC Code, Title, Element ID, Element Nam..."
41,work_context_categories.csv,281,6,"Element ID, Element Name, Scale ID, Scale Name..."
42,work_styles.csv,37422,9,"O*NET-SOC Code, Title, Element ID, Element Nam..."
43,work_styles_to_work_activities.csv,303,4,"Work Styles Element ID, Work Styles Element Na..."
44,work_styles_to_work_context.csv,266,4,"Work Styles Element ID, Work Styles Element Na..."

In [5]:
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 120)

profile_df

,file,rows,columns,column_names
0,abilities.csv,94640,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, N, Standard Error, Lower CI Bound..."
1,abilities_to_work_activities.csv,381,4,"Abilities Element ID, Abilities Element Name, Work Activities Element ID, Work Activities Element Name"
2,abilities_to_work_context.csv,139,4,"Abilities Element ID, Abilities Element Name, Work Context Element ID, Work Context Element Name"
3,career_interest_type_keywords.csv,75,4,"Element ID, Element Name, Keyword, Keyword Type"
4,career_interest_types.csv,8307,9,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, Date, Domain Source"
5,content_model_reference.csv,3006,3,"Element ID, Element Name, Description"
6,education.csv,11495,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Category, Data Value, N, Standard Error, Lowe..."
7,education_categories.csv,24,6,"Element ID, Element Name, Scale ID, Scale Name, Category, Category Description"
8,emerging_tasks.csv,338,8,"O*NET-SOC Code, Title, Task, Category, Original Task ID, Original Task, Date, Domain Source"
9,essential_skills.csv,18200,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, N, Standard Error, Lower CI Bound..."
10,essential_skills_to_work_activities.csv,110,4,"Essential Skills Element ID, Essential Skills Element Name, Work Activities Element ID, Work Activities Element Name"
11,essential_skills_to_work_context.csv,39,4,"Essential Skills Element ID, Essential Skills Element Name, Work Context Element ID, Work Context Element Name"
12,gwas_to_iwas.csv,332,4,"GWA Element ID, GWA Element Name, IWA Element ID, IWA Element Name"
13,gwas_to_iwas_to_dwas.csv,2087,6,"GWA Element ID, GWA Element Name, IWA Element ID, IWA Element Name, DWA Element ID, DWA Element Name"
14,interests_illustrative_activities.csv,188,4,"Element ID, Element Name, Interest Type, Activity"
15,interests_illustrative_occupations.csv,186,5,"Element ID, Element Name, Interest Type, O*NET-SOC Code, Title"
16,job_titles.csv,54269,5,"O*NET-SOC Code, Title, Job Title, Short Title, Source(s)"
17,job_zone_reference.csv,4,7,"Job Zone, Name, Experience, Education, Job Training, Examples, SVP Range"
18,job_zones.csv,923,5,"O*NET-SOC Code, Title, Job Zone, Date, Domain Source"
19,knowledge.csv,60060,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, N, Standard Error, Lower CI Bound..."
20,level_scale_anchors.csv,483,6,"Element ID, Element Name, Scale ID, Scale Name, Anchor Value, Anchor Description"
21,occupation_data.csv,1016,3,"O*NET-SOC Code, Title, Description"
22,occupation_level_metadata.csv,32280,7,"O*NET-SOC Code, Title, Item, Response, N, Percent, Date"
23,related_occupations.csv,18460,6,"O*NET-SOC Code, Title, Related O*NET-SOC Code, Related Title, Relatedness Tier, Index"
24,sample_of_reported_titles.csv,8189,4,"O*NET-SOC Code, Title, Reported Job Title, Shown in My Next Move"
25,scales_reference.csv,33,4,"Scale ID, Scale Name, Minimum, Maximum"
26,software_skills.csv,31821,7,"O*NET-SOC Code, Title, Workplace Example, Element ID, Element Name, Hot Technology, In Demand"
27,specific_interest_areas.csv,73062,9,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, Date, Domain Source"
28,specific_interest_areas_to_career_interest_types.csv,53,4,"Specific Interest Areas Element ID, Specific Interest Areas Element Name, Career Interest Types Element ID, Career I..."
29,survey_booklet_locations.csv,211,5,"Element ID, Element Name, Survey Item Number, Scale ID, Scale Name"
30,task_categories.csv,7,4,"Scale ID, Scale Name, Category, Category Description"
31,task_ratings.csv,165780,15,"O*NET-SOC Code, Title, Task ID, Task, Scale ID, Scale Name, Category, Data Value, N, Standard Error, Lower CI Bound,..."
32,task_statements.csv,18838,8,"O*NET-SOC Code, Title, Task ID, Task, Task Type, Incumbents Responding, Date, Domain Source"
33,tasks_to_dwas.csv,24087,8,"O*NET-SOC Code, Title, Task ID, Task, DWA Element ID, DWA Element Name, Date, Domain Source"
34,training_and_experience.csv,26812,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Category, Data Value, N, Standard Error, Lowe..."
35,training_and_experience_categories.csv,29,6,"Element ID, Element Name, Scale ID, Scale Name, Category, Category Description"
36,transferable_skills.csv,45500,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, N, Standard Error, Lower CI Bound..."
37,transferable_skills_to_work_activities.csv,122,4,"Transferable Skills Element ID, Transferable Skills Element Name, Work Activities Element ID, Work Activities Elemen..."
38,transferable_skills_to_work_context.csv,57,4,"Transferable Skills Element ID, Transferable Skills Element Name, Work Context Element ID, Work Context Element Name"
39,work_activities.csv,74702,15,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, N, Standard Error, Lower CI Bound..."
40,work_context.csv,305389,16,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Category, Data Value, N, Standard Error, Lowe..."
41,work_context_categories.csv,281,6,"Element ID, Element Name, Scale ID, Scale Name, Category, Category Description"
42,work_styles.csv,37422,9,"O*NET-SOC Code, Title, Element ID, Element Name, Scale ID, Scale Name, Data Value, Date, Domain Source"
43,work_styles_to_work_activities.csv,303,4,"Work Styles Element ID, Work Styles Element Name, Work Activities Element ID, Work Activities Element Name"
44,work_styles_to_work_context.csv,266,4,"Work Styles Element ID, Work Styles Element Name, Work Context Element ID, Work Context Element Name"

In [6]:
profile_df[["file", "rows", "columns"]].sort_values(
    "rows", ascending=False
)

                                                    file    rows  columns
40                                      work_context.csv  305389       16
31                                      task_ratings.csv  165780       15
0                                          abilities.csv   94640       15
39                                   work_activities.csv   74702       15
27                           specific_interest_areas.csv   73062        9
19                                         knowledge.csv   60060       15
16                                        job_titles.csv   54269        5
36                               transferable_skills.csv   45500       15
42                                       work_styles.csv   37422        9
22                         occupation_level_metadata.csv   32280        7
26                                   software_skills.csv   31821        7
34                           training_and_experience.csv   26812       15
33                                     tasks_to_dwas.csv   24087        8
32                                   task_statements.csv   18838        8
23                               related_occupations.csv   18460        6
9                                   essential_skills.csv   18200       15
6                                          education.csv   11495       15
4                              career_interest_types.csv    8307        9
24                         sample_of_reported_titles.csv    8189        4
5                            content_model_reference.csv    3006        3
13                              gwas_to_iwas_to_dwas.csv    2087        6
21                                   occupation_data.csv    1016        3
18                                         job_zones.csv     923        5
20                               level_scale_anchors.csv     483        6
1                       abilities_to_work_activities.csv     381        4
8                                     emerging_tasks.csv     338        8
12                                      gwas_to_iwas.csv     332        4
43                    work_styles_to_work_activities.csv     303        4
41                           work_context_categories.csv     281        6
44                       work_styles_to_work_context.csv     266        4
29                          survey_booklet_locations.csv     211        5
14                 interests_illustrative_activities.csv     188        4
15                interests_illustrative_occupations.csv     186        5
2                          abilities_to_work_context.csv     139        4
37            transferable_skills_to_work_activities.csv     122        4
10               essential_skills_to_work_activities.csv     110        4
3                      career_interest_type_keywords.csv      75        4
38               transferable_skills_to_work_context.csv      57        4
28  specific_interest_areas_to_career_interest_types.csv      53        4
11                  essential_skills_to_work_context.csv      39        4
25                                  scales_reference.csv      33        4
35                training_and_experience_categories.csv      29        6
7                               education_categories.csv      24        6
30                                   task_categories.csv       7        4
17                                job_zone_reference.csv       4        7

In [7]:
important_files = [
    "occupation_data.csv",
    "job_titles.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "knowledge.csv",
    "abilities.csv",
    "education.csv",
    "training_and_experience.csv",
    "software_skills.csv",
    "work_activities.csv",
    "task_statements.csv",
    "related_occupations.csv"
]

for filename in important_files:
    filepath = onet_dir / filename
    df = pd.read_csv(filepath)

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)
    print("Shape:", df.shape)
    print("Columns:")
    
    for column in df.columns:
        print("  -", column)

================================================================================
occupation_data.csv
================================================================================
Shape: (1016, 3)
Columns:
  - O*NET-SOC Code
  - Title
  - Description

================================================================================
job_titles.csv
================================================================================
Shape: (54269, 5)
Columns:
  - O*NET-SOC Code
  - Title
  - Job Title
  - Short Title
  - Source(s)

================================================================================
essential_skills.csv
================================================================================
Shape: (18200, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
transferable_skills.csv
================================================================================
Shape: (45500, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
knowledge.csv
================================================================================
Shape: (60060, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
abilities.csv
================================================================================
Shape: (94640, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
education.csv
================================================================================
Shape: (11495, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Category
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Date
  - Domain Source

================================================================================
training_and_experience.csv
================================================================================
Shape: (26812, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Category
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Date
  - Domain Source

================================================================================
software_skills.csv
================================================================================
Shape: (31821, 7)
Columns:
  - O*NET-SOC Code
  - Title
  - Workplace Example
  - Element ID
  - Element Name
  - Hot Technology
  - In Demand

================================================================================
work_activities.csv
================================================================================
Shape: (74702, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
task_statements.csv
================================================================================
Shape: (18838, 8)
Columns:
  - O*NET-SOC Code
  - Title
  - Task ID
  - Task
  - Task Type
  - Incumbents Responding
  - Date
  - Domain Source

================================================================================
related_occupations.csv
================================================================================
Shape: (18460, 6)
Columns:
  - O*NET-SOC Code
  - Title
  - Related O*NET-SOC Code
  - Related Title
  - Relatedness Tier
  - Index

In [8]:
important_files = [
    "occupation_data.csv",
    "job_titles.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "knowledge.csv",
    "abilities.csv",
    "education.csv",
    "training_and_experience.csv",
    "software_skills.csv",
    "work_activities.csv",
    "task_statements.csv",
    "related_occupations.csv"
]

for filename in important_files:
    filepath = onet_dir / filename
    df = pd.read_csv(filepath)

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)
    print("Shape:", df.shape)
    print("Columns:")
    
    for column in df.columns:
        print("  -", column)

================================================================================
occupation_data.csv
================================================================================
Shape: (1016, 3)
Columns:
  - O*NET-SOC Code
  - Title
  - Description

================================================================================
job_titles.csv
================================================================================
Shape: (54269, 5)
Columns:
  - O*NET-SOC Code
  - Title
  - Job Title
  - Short Title
  - Source(s)

================================================================================
essential_skills.csv
================================================================================
Shape: (18200, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
transferable_skills.csv
================================================================================
Shape: (45500, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
knowledge.csv
================================================================================
Shape: (60060, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
abilities.csv
================================================================================
Shape: (94640, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
education.csv
================================================================================
Shape: (11495, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Category
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Date
  - Domain Source

================================================================================
training_and_experience.csv
================================================================================
Shape: (26812, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Category
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Date
  - Domain Source

================================================================================
software_skills.csv
================================================================================
Shape: (31821, 7)
Columns:
  - O*NET-SOC Code
  - Title
  - Workplace Example
  - Element ID
  - Element Name
  - Hot Technology
  - In Demand

================================================================================
work_activities.csv
================================================================================
Shape: (74702, 15)
Columns:
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

================================================================================
task_statements.csv
================================================================================
Shape: (18838, 8)
Columns:
  - O*NET-SOC Code
  - Title
  - Task ID
  - Task
  - Task Type
  - Incumbents Responding
  - Date
  - Domain Source

================================================================================
related_occupations.csv
================================================================================
Shape: (18460, 6)
Columns:
  - O*NET-SOC Code
  - Title
  - Related O*NET-SOC Code
  - Related Title
  - Relatedness Tier
  - Index

In [9]:
for filename in important_files:
    df = pd.read_csv(onet_dir / filename)

    print(f"\n{filename}")
    print(f"Rows: {len(df):,}")

    # Show only columns that can help us connect tables
    key_columns = [
        col for col in df.columns
        if any(keyword in col.lower()
               for keyword in ["code", "id", "title", "name"])
    ]

    print("Potential key/identifier columns:")
    print(key_columns)

occupation_data.csv
Rows: 1,016
Potential key/identifier columns:
['O*NET-SOC Code', 'Title']

job_titles.csv
Rows: 54,269
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Job Title', 'Short Title']

essential_skills.csv
Rows: 18,200
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

transferable_skills.csv
Rows: 45,500
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

knowledge.csv
Rows: 60,060
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

abilities.csv
Rows: 94,640
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

education.csv
Rows: 11,495
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

training_and_experience.csv
Rows: 26,812
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

software_skills.csv
Rows: 31,821
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name']

work_activities.csv
Rows: 74,702
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name']

task_statements.csv
Rows: 18,838
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Task ID']

related_occupations.csv
Rows: 18,460
Potential key/identifier columns:
['O*NET-SOC Code', 'Title', 'Related O*NET-SOC Code', 'Related Title']

In [10]:
# ============================================================
# STAGE 2 — PROFILE THE CORE CAREER-INTELLIGENCE TABLES
# ============================================================

import pandas as pd
from pathlib import Path

# O*NET data directory
DATA_DIR = Path("/home/Student/career-intelligence/data/raw/onet/db_31_0_csv")

# Core tables we identified from the first profiling stage
core_files = [
    "job_titles.csv",
    "abilities.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "knowledge.csv",
    "education.csv",
    "training_and_experience.csv",
    "software_skills.csv",
    "work_activities.csv",
    "task_statements.csv",
    "related_occupations.csv"
]

for filename in core_files:

    filepath = DATA_DIR / filename

    print("\n" + "=" * 80)
    print(f"FILE: {filename}")
    print("=" * 80)

    df = pd.read_csv(filepath)

    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")

    print("\nColumns:")
    print(list(df.columns))

    print("\nMissing values:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No missing values.")
    else:
        print(missing.sort_values(ascending=False))

    print("\nDuplicate rows:")
    print(df.duplicated().sum())

    print("\nUnique O*NET-SOC codes:")
    if "*O*NET-SOC Code" in df.columns:
        print(df["*O*NET-SOC Code"].nunique())

    print("\nFirst 3 rows:")
    display(df.head(3))

================================================================================
FILE: job_titles.csv
================================================================================
Rows: 54,269
Columns: 5

Columns:
['O*NET-SOC Code', 'Title', 'Job Title', 'Short Title', 'Source(s)']

Missing values:
Short Title    49814
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Job Title,Short Title,Source(s)
0,11-1011.00,Chief Executives,Aeronautics Commission Director,NaN,08
1,11-1011.00,Chief Executives,Agency Owner,NaN,10
2,11-1011.00,Chief Executives,Agricultural Services Director,NaN,08

================================================================================
FILE: abilities.csv
================================================================================
Rows: 94,640
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant    47320
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,IM,Importance,4.62,8,0.1830,4.2664,4.9836,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst

================================================================================
FILE: essential_skills.csv
================================================================================
Rows: 18,200
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant    9100
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.125,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.183,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.000,4.0000,4.0000,N,NaN,08/2023,Analyst

================================================================================
FILE: transferable_skills.csv
================================================================================
Rows: 45,500
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant    22750
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.B.1.b,Coordination,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst

================================================================================
FILE: knowledge.csv
================================================================================
Rows: 60,060
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant          30030
Lower CI Bound        17698
Upper CI Bound        17698
Standard Error        16962
Recommend Suppress    16434
N                       594
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,IM,Importance,4.78,28.0,0.1102,4.5564,5.0000,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,LV,Level,6.50,28.0,0.2130,6.0666,6.9409,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.C.1.b,Administrative,IM,Importance,2.42,28.0,0.4651,1.4662,3.3749,N,NaN,08/2023,Incumbent

================================================================================
FILE: education.csv
================================================================================
Rows: 11,495
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

Missing values:
Lower CI Bound        7883
Upper CI Bound        7883
Standard Error        3121
Recommend Suppress    3121
Category               683
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
0,11-1011.00,Chief Executives,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),1.0,0.00,28,0.0000,NaN,NaN,N,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),2.0,4.46,28,4.1428,0.6307,25.5524,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),3.0,0.00,28,0.0000,NaN,NaN,N,08/2023,Incumbent

================================================================================
FILE: training_and_experience.csv
================================================================================
Rows: 26,812
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

Missing values:
Lower CI Bound        13210
Upper CI Bound        13210
Standard Error         7433
Recommend Suppress     7433
Category                683
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
0,11-1011.00,Chief Executives,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),1.0,0.0,28,0.0,NaN,NaN,N,08/2023,Incumbent
1,11-1011.00,Chief Executives,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),2.0,0.0,28,0.0,NaN,NaN,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),3.0,0.0,28,0.0,NaN,NaN,N,08/2023,Incumbent

================================================================================
FILE: software_skills.csv
================================================================================
Rows: 31,821
Columns: 7

Columns:
['O*NET-SOC Code', 'Title', 'Workplace Example', 'Element ID', 'Element Name', 'Hot Technology', 'In Demand']

Missing values:
No missing values.

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N

================================================================================
FILE: work_activities.csv
================================================================================
Rows: 74,702
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant          37351
Lower CI Bound        21098
Upper CI Bound        21098
Standard Error        21074
Recommend Suppress    20418
N                       738
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,IM,Importance,4.56,29.0,0.1559,4.2369,4.8756,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,LV,Level,4.89,30.0,0.1727,4.5393,5.2458,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,4.25,30.0,0.2125,3.8130,4.6823,N,NaN,08/2023,Incumbent

================================================================================
FILE: task_statements.csv
================================================================================
Rows: 18,838
Columns: 8

Columns:
['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type', 'Incumbents Responding', 'Date', 'Domain Source']

Missing values:
Incumbents Responding    587
Task Type                418
dtype: int64

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,"Direct or coordinate an organization's financial or budget activities to fund operations, maximize investments, or i...",Core,95.0,08/2023,Incumbent
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization officials, or staff members to discuss issues, coordinate activities, or res...",Core,95.0,08/2023,Incumbent
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those for funding or implementation of programs.",Core,95.0,08/2023,Incumbent

================================================================================
FILE: related_occupations.csv
================================================================================
Rows: 18,460
Columns: 6

Columns:
['O*NET-SOC Code', 'Title', 'Related O*NET-SOC Code', 'Related Title', 'Relatedness Tier', 'Index']

Missing values:
No missing values.

Duplicate rows:
0

Unique O*NET-SOC codes:

First 3 rows:

,O*NET-SOC Code,Title,Related O*NET-SOC Code,Related Title,Relatedness Tier,Index
0,11-1011.00,Chief Executives,11-1021.00,General and Operations Managers,Primary-Short,1
1,11-1011.00,Chief Executives,13-1111.00,Management Analysts,Primary-Short,2
2,11-1011.00,Chief Executives,11-3031.01,Treasurers and Controllers,Primary-Short,3

In [1]:
import pandas as pd
from pathlib import Path

# O*NET data directory
DATA_DIR = Path("/home/Student/career-intelligence/data/raw/onet/db_31_0_csv")

# Core tables for the Career Intelligence Platform
core_files = [
    "job_titles.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "software_skills.csv",
    "knowledge.csv",
    "abilities.csv",
    "education.csv",
    "training_and_experience.csv",
    "work_activities.csv",
    "task_statements.csv",
    "related_occupations.csv"
]

for filename in core_files:
    path = DATA_DIR / filename
    df = pd.read_csv(path)

    print("\n" + "=" * 80)
    print(f"FILE: {filename}")
    print("=" * 80)

    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")

    print("\nColumns:")
    print(list(df.columns))

    print("\nMissing values:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) == 0:
        print("None")
    else:
        print(missing)

    print("\nDuplicate rows:", df.duplicated().sum())

================================================================================
FILE: job_titles.csv
================================================================================
Rows: 54,269
Columns: 5

Columns:
['O*NET-SOC Code', 'Title', 'Job Title', 'Short Title', 'Source(s)']

Missing values:
Short Title    49814
dtype: int64

Duplicate rows: 0

================================================================================
FILE: essential_skills.csv
================================================================================
Rows: 18,200
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant    9100
dtype: int64

Duplicate rows: 0

================================================================================
FILE: transferable_skills.csv
================================================================================
Rows: 45,500
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant    22750
dtype: int64

Duplicate rows: 0

================================================================================
FILE: software_skills.csv
================================================================================
Rows: 31,821
Columns: 7

Columns:
['O*NET-SOC Code', 'Title', 'Workplace Example', 'Element ID', 'Element Name', 'Hot Technology', 'In Demand']

Missing values:
None

Duplicate rows: 0

================================================================================
FILE: knowledge.csv
================================================================================
Rows: 60,060
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
N                       594
Standard Error        16962
Lower CI Bound        17698
Upper CI Bound        17698
Recommend Suppress    16434
Not Relevant          30030
dtype: int64

Duplicate rows: 0

================================================================================
FILE: abilities.csv
================================================================================
Rows: 94,640
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
Not Relevant    47320
dtype: int64

Duplicate rows: 0

================================================================================
FILE: education.csv
================================================================================
Rows: 11,495
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

Missing values:
Category               683
Standard Error        3121
Lower CI Bound        7883
Upper CI Bound        7883
Recommend Suppress    3121
dtype: int64

Duplicate rows: 0

================================================================================
FILE: training_and_experience.csv
================================================================================
Rows: 26,812
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

Missing values:
Category                683
Standard Error         7433
Lower CI Bound        13210
Upper CI Bound        13210
Recommend Suppress     7433
dtype: int64

Duplicate rows: 0

================================================================================
FILE: work_activities.csv
================================================================================
Rows: 74,702
Columns: 15

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

Missing values:
N                       738
Standard Error        21074
Lower CI Bound        21098
Upper CI Bound        21098
Recommend Suppress    20418
Not Relevant          37351
dtype: int64

Duplicate rows: 0

================================================================================
FILE: task_statements.csv
================================================================================
Rows: 18,838
Columns: 8

Columns:
['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type', 'Incumbents Responding', 'Date', 'Domain Source']

Missing values:
Task Type                418
Incumbents Responding    587
dtype: int64

Duplicate rows: 0

================================================================================
FILE: related_occupations.csv
================================================================================
Rows: 18,460
Columns: 6

Columns:
['O*NET-SOC Code', 'Title', 'Related O*NET-SOC Code', 'Related Title', 'Relatedness Tier', 'Index']

Missing values:
None

Duplicate rows: 0

In [2]:
# ============================================================
# STAGE 2 — PROFILE THE CORE CAREER INTELLIGENCE TABLES
# ============================================================

core_files = [
    "job_titles.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "software_skills.csv",
    "knowledge.csv",
    "abilities.csv",
    "education.csv",
    "training_and_experience.csv",
    "work_activities.csv",
    "task_statements.csv",
    "related_occupations.csv"
]

for filename in core_files:

    df = pd.read_csv(DATA_DIR / filename)

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)

    print("Rows:", f"{len(df):,}")
    print("Columns:", len(df.columns))

    print("\nFirst 3 rows:")
    display(df.head(3))

    print("\nData types:")
    print(df.dtypes)

    print("\nUnique O*NET-SOC codes:",
          df["O*NET-SOC Code"].nunique()
          if "O*NET-SOC Code" in df.columns
          else "No O*NET-SOC Code column")

================================================================================
job_titles.csv
================================================================================
Rows: 54,269
Columns: 5

First 3 rows:

,O*NET-SOC Code,Title,Job Title,Short Title,Source(s)
0,11-1011.00,Chief Executives,Aeronautics Commission Director,NaN,08
1,11-1011.00,Chief Executives,Agency Owner,NaN,10
2,11-1011.00,Chief Executives,Agricultural Services Director,NaN,08

Data types:
O*NET-SOC Code    object
Title             object
Job Title         object
Short Title       object
Source(s)         object
dtype: object

Unique O*NET-SOC codes: 1016

================================================================================
essential_skills.csv
================================================================================
Rows: 18,200
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.125,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.183,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.000,4.0000,4.0000,N,NaN,08/2023,Analyst

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Data Value            float64
N                       int64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Not Relevant           object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 910

================================================================================
transferable_skills.csv
================================================================================
Rows: 45,500
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.B.1.b,Coordination,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Data Value            float64
N                       int64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Not Relevant           object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 910

================================================================================
software_skills.csv
================================================================================
Rows: 31,821
Columns: 7

First 3 rows:

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N

Data types:
O*NET-SOC Code       object
Title                object
Workplace Example    object
Element ID           object
Element Name         object
Hot Technology       object
In Demand            object
dtype: object

Unique O*NET-SOC codes: 923

================================================================================
knowledge.csv
================================================================================
Rows: 60,060
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,IM,Importance,4.78,28.0,0.1102,4.5564,5.0000,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,LV,Level,6.50,28.0,0.2130,6.0666,6.9409,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.C.1.b,Administrative,IM,Importance,2.42,28.0,0.4651,1.4662,3.3749,N,NaN,08/2023,Incumbent

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Data Value            float64
N                     float64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Not Relevant           object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 910

================================================================================
abilities.csv
================================================================================
Rows: 94,640
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,IM,Importance,4.62,8,0.1830,4.2664,4.9836,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Data Value            float64
N                       int64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Not Relevant           object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 910

================================================================================
education.csv
================================================================================
Rows: 11,495
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
0,11-1011.00,Chief Executives,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),1.0,0.00,28,0.0000,NaN,NaN,N,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),2.0,4.46,28,4.1428,0.6307,25.5524,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),3.0,0.00,28,0.0000,NaN,NaN,N,08/2023,Incumbent

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Category              float64
Data Value            float64
N                       int64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 901

================================================================================
training_and_experience.csv
================================================================================
Rows: 26,812
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
0,11-1011.00,Chief Executives,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),1.0,0.0,28,0.0,NaN,NaN,N,08/2023,Incumbent
1,11-1011.00,Chief Executives,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),2.0,0.0,28,0.0,NaN,NaN,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),3.0,0.0,28,0.0,NaN,NaN,N,08/2023,Incumbent

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Category              float64
Data Value            float64
N                       int64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 901

================================================================================
work_activities.csv
================================================================================
Rows: 74,702
Columns: 15

First 3 rows:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,IM,Importance,4.56,29.0,0.1559,4.2369,4.8756,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,LV,Level,4.89,30.0,0.1727,4.5393,5.2458,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,4.25,30.0,0.2125,3.8130,4.6823,N,NaN,08/2023,Incumbent

Data types:
O*NET-SOC Code         object
Title                  object
Element ID             object
Element Name           object
Scale ID               object
Scale Name             object
Data Value            float64
N                     float64
Standard Error        float64
Lower CI Bound        float64
Upper CI Bound        float64
Recommend Suppress     object
Not Relevant           object
Date                   object
Domain Source          object
dtype: object

Unique O*NET-SOC codes: 911

================================================================================
task_statements.csv
================================================================================
Rows: 18,838
Columns: 8

First 3 rows:

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent

Data types:
O*NET-SOC Code            object
Title                     object
Task ID                    int64
Task                      object
Task Type                 object
Incumbents Responding    float64
Date                      object
Domain Source             object
dtype: object

Unique O*NET-SOC codes: 923

================================================================================
related_occupations.csv
================================================================================
Rows: 18,460
Columns: 6

First 3 rows:

,O*NET-SOC Code,Title,Related O*NET-SOC Code,Related Title,Relatedness Tier,Index
0,11-1011.00,Chief Executives,11-1021.00,General and Operations Managers,Primary-Short,1
1,11-1011.00,Chief Executives,13-1111.00,Management Analysts,Primary-Short,2
2,11-1011.00,Chief Executives,11-3031.01,Treasurers and Controllers,Primary-Short,3

Data types:
O*NET-SOC Code            object
Title                     object
Related O*NET-SOC Code    object
Related Title             object
Relatedness Tier          object
Index                      int64
dtype: object

Unique O*NET-SOC codes: 923

In [3]:
# ============================================================
# STAGE 2 — CHECK HOW OUR CORE TABLES CONNECT
# ============================================================

files_to_check = [
    "job_titles.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "software_skills.csv",
    "knowledge.csv",
    "education.csv",
    "training_and_experience.csv",
    "work_activities.csv",
    "task_statements.csv"
]

for filename in files_to_check:
    df = pd.read_csv(DATA_DIR / filename)

    print(f"\n{filename}")
    print("-" * 60)

    if "O*NET-SOC Code" in df.columns:
        print("Unique occupations:",
              df["O*NET-SOC Code"].nunique())

        print("Example occupation codes:",
              df["O*NET-SOC Code"].dropna().unique()[:5])

    else:
        print("No O*NET-SOC Code column")

job_titles.csv
------------------------------------------------------------
Unique occupations: 1016
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-1031.00' '11-2011.00']

essential_skills.csv
------------------------------------------------------------
Unique occupations: 910
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-2011.00' '11-2021.00']

transferable_skills.csv
------------------------------------------------------------
Unique occupations: 910
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-2011.00' '11-2021.00']

software_skills.csv
------------------------------------------------------------
Unique occupations: 923
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-1031.00' '11-2011.00']

knowledge.csv
------------------------------------------------------------
Unique occupations: 910
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-2011.00' '11-2021.00']

education.csv
------------------------------------------------------------
Unique occupations: 901
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-2011.00' '11-2021.00']

training_and_experience.csv
------------------------------------------------------------
Unique occupations: 901
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-2011.00' '11-2021.00']

work_activities.csv
------------------------------------------------------------
Unique occupations: 911
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-2011.00' '11-2021.00']

task_statements.csv
------------------------------------------------------------
Unique occupations: 923
Example occupation codes: ['11-1011.00' '11-1011.03' '11-1021.00' '11-1031.00' '11-2011.00']

In [4]:
# ============================================================
# STAGE 3 — EXPLORE ONE CAREER
# ============================================================

# Load job titles
job_titles = pd.read_csv(DATA_DIR / "job_titles.csv")

# Search for Data Analyst
data_analyst = job_titles[
    job_titles["Job Title"].str.contains(
        "Data Analyst",
        case=False,
        na=False
    )
]

print("Data Analyst matches:")
display(data_analyst)

Data Analyst matches:

,O*NET-SOC Code,Title,Job Title,Short Title,Source(s)
2966,13-1081.02,Logistics Analysts,Supply Chain Data Analyst,NaN,10
3009,13-1111.00,Management Analysts,Health Information Management Data Analyst (HI...,HIM Data Analyst,"03,08"
4179,13-2099.01,Financial Quantitative Analysts,Data Analyst,NaN,10
4224,13-2099.04,"Fraud Examiners, Investigators and Analysts",Fraud Data Analyst,NaN,10
4320,15-1211.01,Health Informatics Specialists,Healthcare Data Analyst,NaN,10
4742,15-1243.00,Database Architects,Data Analyst,NaN,08
5596,15-2041.00,Statisticians,Data Analyst,NaN,"03,08,10"
5597,15-2041.00,Statisticians,Data Analyst Specialist,NaN,10
5619,15-2041.00,Statisticians,Statistical Data Analyst,NaN,10
5644,15-2051.00,Data Scientists,Data Analyst,NaN,08
5674,15-2051.01,Business Intelligence Analysts,Business Data Analyst,NaN,10
5687,15-2051.01,Business Intelligence Analysts,Data Analyst,NaN,"02,08,10"
5705,15-2051.02,Clinical Data Managers,Clinical Data Analyst,NaN,08
5732,15-2099.01,Bioinformatics Technicians,Bioinformatics Data Analyst,NaN,02
7572,17-3027.00,Mechanical Engineering Technologists and Techn...,Engineering Data Analyst,NaN,10
8044,19-1029.01,Bioinformatics Scientists,Data Analyst,NaN,10
8606,19-2042.00,"Geoscientists, Except Hydrologists and Geograp...",Mud Logging Data Analyst,NaN,03
8737,19-3022.00,Survey Researchers,Data Analyst,NaN,"02,10"
9644,19-4061.00,Social Science Research Assistants,Data Analyst,NaN,"02,10"
9662,19-4061.00,Social Science Research Assistants,Research Data Analyst,NaN,10
18103,29-9021.00,Health Information Technologists and Medical R...,Health Data Analyst,NaN,08
18111,29-9021.00,Health Information Technologists and Medical R...,Healthcare Data Analyst,NaN,08
18114,29-9021.00,Health Information Technologists and Medical R...,Medical Data Analyst,NaN,08

In [5]:
# ============================================================
# STAGE 4 — INSPECT DATA ANALYST / BUSINESS INTELLIGENCE
# ============================================================

occupation_code = "15-2051.01"

# Load the relevant tables
job_titles = pd.read_csv(DATA_DIR / "job_titles.csv")
essential_skills = pd.read_csv(DATA_DIR / "essential_skills.csv")
transferable_skills = pd.read_csv(DATA_DIR / "transferable_skills.csv")
software_skills = pd.read_csv(DATA_DIR / "software_skills.csv")
knowledge = pd.read_csv(DATA_DIR / "knowledge.csv")

# Show job titles belonging to this occupation
print("=" * 80)
print("JOB TITLES")
print("=" * 80)

display(
    job_titles[
        job_titles["O*NET-SOC Code"] == occupation_code
    ][
        ["O*NET-SOC Code", "Title", "Job Title", "Short Title"]
    ]
)

# Show essential skills
print("=" * 80)
print("ESSENTIAL SKILLS")
print("=" * 80)

display(
    essential_skills[
        essential_skills["O*NET-SOC Code"] == occupation_code
    ]
)

# Show transferable skills
print("=" * 80)
print("TRANSFERABLE SKILLS")
print("=" * 80)

display(
    transferable_skills[
        transferable_skills["O*NET-SOC Code"] == occupation_code
    ]
)

# Show software skills
print("=" * 80)
print("SOFTWARE SKILLS")
print("=" * 80)

display(
    software_skills[
        software_skills["O*NET-SOC Code"] == occupation_code
    ]
)

# Show knowledge areas
print("=" * 80)
print("KNOWLEDGE")
print("=" * 80)

display(
    knowledge[
        knowledge["O*NET-SOC Code"] == occupation_code
    ]
)

================================================================================
JOB TITLES
================================================================================

,O*NET-SOC Code,Title,Job Title,Short Title
5671,15-2051.01,Business Intelligence Analysts,Analytical Data Miner,NaN
5672,15-2051.01,Business Intelligence Analysts,Business Analyst,NaN
5673,15-2051.01,Business Intelligence Analysts,Business Consultant,NaN
5674,15-2051.01,Business Intelligence Analysts,Business Data Analyst,NaN
5675,15-2051.01,Business Intelligence Analysts,Business Database Analyst,NaN
5676,15-2051.01,Business Intelligence Analysts,Business Information Analyst,NaN
5677,15-2051.01,Business Intelligence Analysts,Business Intelligence Analyst (BI Analyst),BI Analyst
5678,15-2051.01,Business Intelligence Analysts,Business Intelligence Consultant (BI Consultant),BI Consultant
5679,15-2051.01,Business Intelligence Analysts,Business Intelligence Coordinator (BI Coordina...,BI Coordinator
5680,15-2051.01,Business Intelligence Analysts,Business Intelligence Engineer,NaN
5681,15-2051.01,Business Intelligence Analysts,Business Intelligence Specialist (BI Specialist),BI Specialist
5682,15-2051.01,Business Intelligence Analysts,Business Process Analyst,NaN
5683,15-2051.01,Business Intelligence Analysts,Business Systems Analyst,NaN
5684,15-2051.01,Business Intelligence Analysts,Business Systems Consultant,NaN
5685,15-2051.01,Business Intelligence Analysts,Business Technology Consultant,NaN
5686,15-2051.01,Business Intelligence Analysts,Competitive Intelligence Analyst,NaN
5687,15-2051.01,Business Intelligence Analysts,Data Analyst,NaN
5688,15-2051.01,Business Intelligence Analysts,EDI Analyst (Electronic Data Interchange Analyst),EDI Analyst
5689,15-2051.01,Business Intelligence Analysts,Information Analyst,NaN
5690,15-2051.01,Business Intelligence Analysts,Information Specialist,NaN
5691,15-2051.01,Business Intelligence Analysts,Intelligence Analyst,NaN
5692,15-2051.01,Business Intelligence Analysts,Market Intelligence Analyst,NaN
5693,15-2051.01,Business Intelligence Analysts,Market Intelligence Consultant,NaN
5694,15-2051.01,Business Intelligence Analysts,Marketing Database Analyst,NaN
5695,15-2051.01,Business Intelligence Analysts,Reporting Analyst,NaN
5696,15-2051.01,Business Intelligence Analysts,Reports Analyst,NaN
5697,15-2051.01,Business Intelligence Analysts,Strategic Business and Technology Intelligence...,NaN

================================================================================
ESSENTIAL SKILLS
================================================================================

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
2680,15-2051.01,Business Intelligence Analysts,2.A.1.a,Reading Comprehension,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2024,Analyst
2681,15-2051.01,Business Intelligence Analysts,2.A.1.a,Reading Comprehension,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2024,Analyst
2682,15-2051.01,Business Intelligence Analysts,2.A.1.b,Active Listening,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2683,15-2051.01,Business Intelligence Analysts,2.A.1.b,Active Listening,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
2684,15-2051.01,Business Intelligence Analysts,2.A.1.c,Writing,IM,Importance,3.75,8,0.1637,3.4292,4.0708,N,NaN,08/2024,Analyst
2685,15-2051.01,Business Intelligence Analysts,2.A.1.c,Writing,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
2686,15-2051.01,Business Intelligence Analysts,2.A.1.d,Speaking,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2687,15-2051.01,Business Intelligence Analysts,2.A.1.d,Speaking,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
2688,15-2051.01,Business Intelligence Analysts,2.A.1.e,Mathematics,IM,Importance,3.50,8,0.1890,3.1296,3.8704,N,NaN,08/2024,Analyst
2689,15-2051.01,Business Intelligence Analysts,2.A.1.e,Mathematics,LV,Level,3.88,8,0.2266,3.4309,4.3191,N,N,08/2024,Analyst
2690,15-2051.01,Business Intelligence Analysts,2.A.1.f,Science,IM,Importance,1.62,8,0.1830,1.2664,1.9836,N,NaN,08/2024,Analyst
2691,15-2051.01,Business Intelligence Analysts,2.A.1.f,Science,LV,Level,0.75,8,0.2500,0.2600,1.2400,N,N,08/2024,Analyst
2692,15-2051.01,Business Intelligence Analysts,2.A.2.a,Critical Thinking,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2693,15-2051.01,Business Intelligence Analysts,2.A.2.a,Critical Thinking,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2024,Analyst
2694,15-2051.01,Business Intelligence Analysts,2.A.2.b,Active Learning,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2695,15-2051.01,Business Intelligence Analysts,2.A.2.b,Active Learning,LV,Level,4.12,8,0.1250,3.8800,4.3700,N,N,08/2024,Analyst
2696,15-2051.01,Business Intelligence Analysts,2.A.2.c,Learning Strategies,IM,Importance,3.00,8,0.0000,3.0000,3.0000,N,NaN,08/2024,Analyst
2697,15-2051.01,Business Intelligence Analysts,2.A.2.c,Learning Strategies,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
2698,15-2051.01,Business Intelligence Analysts,2.A.2.d,Monitoring,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
2699,15-2051.01,Business Intelligence Analysts,2.A.2.d,Monitoring,LV,Level,3.25,8,0.1637,2.9292,3.5708,N,N,08/2024,Analyst

================================================================================
TRANSFERABLE SKILLS
================================================================================

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
6700,15-2051.01,Business Intelligence Analysts,2.B.1.a,Social Perceptiveness,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2024,Analyst
6701,15-2051.01,Business Intelligence Analysts,2.B.1.a,Social Perceptiveness,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2024,Analyst
6702,15-2051.01,Business Intelligence Analysts,2.B.1.b,Coordination,IM,Importance,3.00,8,0.0000,3.0000,3.0000,N,NaN,08/2024,Analyst
6703,15-2051.01,Business Intelligence Analysts,2.B.1.b,Coordination,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
6704,15-2051.01,Business Intelligence Analysts,2.B.1.c,Persuasion,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2024,Analyst
6705,15-2051.01,Business Intelligence Analysts,2.B.1.c,Persuasion,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
6706,15-2051.01,Business Intelligence Analysts,2.B.1.d,Negotiation,IM,Importance,2.50,8,0.1890,2.1296,2.8704,N,NaN,08/2024,Analyst
6707,15-2051.01,Business Intelligence Analysts,2.B.1.d,Negotiation,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2024,Analyst
6708,15-2051.01,Business Intelligence Analysts,2.B.1.e,Instructing,IM,Importance,3.00,8,0.0000,3.0000,3.0000,N,NaN,08/2024,Analyst
6709,15-2051.01,Business Intelligence Analysts,2.B.1.e,Instructing,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
6710,15-2051.01,Business Intelligence Analysts,2.B.1.f,Service Orientation,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2024,Analyst
6711,15-2051.01,Business Intelligence Analysts,2.B.1.f,Service Orientation,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2024,Analyst
6712,15-2051.01,Business Intelligence Analysts,2.B.2.i,Complex Problem Solving,IM,Importance,3.38,8,0.1830,3.0164,3.7336,N,NaN,08/2024,Analyst
6713,15-2051.01,Business Intelligence Analysts,2.B.2.i,Complex Problem Solving,LV,Level,3.75,8,0.1637,3.4292,4.0708,N,N,08/2024,Analyst
6714,15-2051.01,Business Intelligence Analysts,2.B.3.a,Operations Analysis,IM,Importance,1.88,8,0.2266,1.4309,2.3191,N,NaN,08/2024,Analyst
6715,15-2051.01,Business Intelligence Analysts,2.B.3.a,Operations Analysis,LV,Level,1.62,8,0.3750,0.8900,2.3600,N,N,08/2024,Analyst
6716,15-2051.01,Business Intelligence Analysts,2.B.3.b,Technology Design,IM,Importance,1.62,8,0.1830,1.2664,1.9836,N,NaN,08/2024,Analyst
6717,15-2051.01,Business Intelligence Analysts,2.B.3.b,Technology Design,LV,Level,0.88,8,0.2950,0.2967,1.4533,N,N,08/2024,Analyst
6718,15-2051.01,Business Intelligence Analysts,2.B.3.c,Equipment Selection,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6719,15-2051.01,Business Intelligence Analysts,2.B.3.c,Equipment Selection,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6720,15-2051.01,Business Intelligence Analysts,2.B.3.d,Installation,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6721,15-2051.01,Business Intelligence Analysts,2.B.3.d,Installation,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6722,15-2051.01,Business Intelligence Analysts,2.B.3.e,Programming,IM,Importance,2.50,8,0.1890,2.1296,2.8704,N,NaN,08/2024,Analyst
6723,15-2051.01,Business Intelligence Analysts,2.B.3.e,Programming,LV,Level,2.50,8,0.1890,2.1296,2.8704,N,N,08/2024,Analyst
6724,15-2051.01,Business Intelligence Analysts,2.B.3.g,Operations Monitoring,IM,Importance,1.75,8,0.1637,1.4292,2.0708,N,NaN,08/2024,Analyst
6725,15-2051.01,Business Intelligence Analysts,2.B.3.g,Operations Monitoring,LV,Level,1.12,8,0.2950,0.5467,1.7033,N,N,08/2024,Analyst
6726,15-2051.01,Business Intelligence Analysts,2.B.3.h,Operation and Control,IM,Importance,1.38,8,0.1830,1.0164,1.7336,N,NaN,08/2024,Analyst
6727,15-2051.01,Business Intelligence Analysts,2.B.3.h,Operation and Control,LV,Level,0.38,8,0.1830,0.0164,0.7336,N,N,08/2024,Analyst
6728,15-2051.01,Business Intelligence Analysts,2.B.3.j,Equipment Maintenance,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6729,15-2051.01,Business Intelligence Analysts,2.B.3.j,Equipment Maintenance,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6730,15-2051.01,Business Intelligence Analysts,2.B.3.k,Troubleshooting,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6731,15-2051.01,Business Intelligence Analysts,2.B.3.k,Troubleshooting,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6732,15-2051.01,Business Intelligence Analysts,2.B.3.l,Repairing,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6733,15-2051.01,Business Intelligence Analysts,2.B.3.l,Repairing,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6734,15-2051.01,Business Intelligence Analysts,2.B.3.m,Quality Control Analysis,IM,Importance,2.00,8,0.1890,1.6296,2.3704,N,NaN,08/2024,Analyst
6735,15-2051.01,Business Intelligence Analysts,2.B.3.m,Quality Control Analysis,LV,Level,1.50,8,0.3273,0.8584,2.1416,N,N,08/2024,Analyst
6736,15-2051.01,Business Intelligence Analysts,2.B.4.e,Judgment and Decision Making,IM,Importance,3.62,8,0.1830,3.2664,3.9836,N,NaN,08/2024,Analyst
6737,15-2051.01,Business Intelligence Analysts,2.B.4.e,Judgment and Decision Making,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
6738,15-2051.01,Business Intelligence Analysts,2.B.4.g,Systems Analysis,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
6739,15-2051.01,Business Intelligence Analysts,2.B.4.g,Systems Analysis,LV,Level,3.75,8,0.1637,3.4292,4.0708,N,N,08/2024,Analyst
6740,15-2051.01,Business Intelligence Analysts,2.B.4.h,Systems Evaluation,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
6741,15-2051.01,Business Intelligence Analysts,2.B.4.h,Systems Evaluation,LV,Level,3.75,8,0.1637,3.4292,4.0708,N,N,08/2024,Analyst
6742,15-2051.01,Business Intelligence Analysts,2.B.5.a,Time Management,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
6743,15-2051.01,Business Intelligence Analysts,2.B.5.a,Time Management,LV,Level,3.00,8,0.1890,2.6296,3.3704,N,N,08/2024,Analyst
6744,15-2051.01,Business Intelligence Analysts,2.B.5.b,Management of Financial Resources,IM,Importance,1.88,8,0.1250,1.6300,2.1200,N,NaN,08/2024,Analyst
6745,15-2051.01,Business Intelligence Analysts,2.B.5.b,Management of Financial Resources,LV,Level,1.75,8,0.2500,1.2600,2.2400,N,N,08/2024,Analyst
6746,15-2051.01,Business Intelligence Analysts,2.B.5.c,Management of Material Resources,IM,Importance,1.75,8,0.1637,1.4292,2.0708,N,NaN,08/2024,Analyst
6747,15-2051.01,Business Intelligence Analysts,2.B.5.c,Management of Material Resources,LV,Level,1.25,8,0.3134,0.6358,1.8642,N,N,08/2024,Analyst
6748,15-2051.01,Business Intelligence Analysts,2.B.5.d,Management of Personnel Resources,IM,Importance,2.12,8,0.1250,1.8800,2.3700,N,NaN,08/2024,Analyst
6749,15-2051.01,Business Intelligence Analysts,2.B.5.d,Management of Personnel Resources,LV,Level,2.00,8,0.1890,1.6296,2.3704,N,N,08/2024,Analyst

================================================================================
SOFTWARE SKILLS
================================================================================

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
11952,15-2051.01,Business Intelligence Analysts,Actuate Eclipse BIRT,2.E.6.e,Data base reporting software,N,N
11953,15-2051.01,Business Intelligence Analysts,Adobe Acrobat,2.E.5.b,Document management software,Y,N
11954,15-2051.01,Business Intelligence Analysts,Adobe ActionScript,2.E.7.b,Development environment software,N,N
11955,15-2051.01,Business Intelligence Analysts,Adobe Dreamweaver,2.E.4.g,Web page creation and editing software,N,N
11956,15-2051.01,Business Intelligence Analysts,Advanced business application programming ABAP,2.E.7.e,Object or component oriented development software,N,N
...,...,...,...,...,...,...,...
12150,15-2051.01,Business Intelligence Analysts,UNIX Shell,2.E.13.c,Operating system software,Y,N
12151,15-2051.01,Business Intelligence Analysts,Veritas NetBackup,2.E.15.f,Backup or archival software,N,N
12152,15-2051.01,Business Intelligence Analysts,Virtual private networking VPN software,2.E.14.c,Network security and virtual private network V...,N,N
12153,15-2051.01,Business Intelligence Analysts,Wireshark,2.E.11.a,Network monitoring software,N,N
12154,15-2051.01,Business Intelligence Analysts,YouTube,2.E.4.c,Video creation and editing software,N,N

================================================================================
KNOWLEDGE
================================================================================

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
8844,15-2051.01,Business Intelligence Analysts,2.C.1.a,Administration and Management,IM,Importance,3.14,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8845,15-2051.01,Business Intelligence Analysts,2.C.1.a,Administration and Management,LV,Level,4.14,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8846,15-2051.01,Business Intelligence Analysts,2.C.1.b,Administrative,IM,Importance,2.43,21.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8847,15-2051.01,Business Intelligence Analysts,2.C.1.b,Administrative,LV,Level,3.64,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8848,15-2051.01,Business Intelligence Analysts,2.C.1.c,Economics and Accounting,IM,Importance,3.00,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8905,15-2051.01,Business Intelligence Analysts,2.C.9.a,Telecommunications,LV,Level,1.14,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8906,15-2051.01,Business Intelligence Analysts,2.C.9.b,Communications and Media,IM,Importance,2.59,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8907,15-2051.01,Business Intelligence Analysts,2.C.9.b,Communications and Media,LV,Level,2.95,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8908,15-2051.01,Business Intelligence Analysts,2.C.10,Transportation,IM,Importance,1.18,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8909,15-2051.01,Business Intelligence Analysts,2.C.10,Transportation,LV,Level,0.55,22.0,NaN,NaN,NaN,NaN,Y,08/2024,Occupational Expert

In [6]:
# ============================================================
# STAGE 5 — UNDERSTAND THE SKILL DATA
# ============================================================

print("ESSENTIAL SKILLS COLUMNS")
print(list(essential_skills.columns))

print("\nTRANSFERABLE SKILLS COLUMNS")
print(list(transferable_skills.columns))

print("\nSOFTWARE SKILLS COLUMNS")
print(list(software_skills.columns))

ESSENTIAL SKILLS COLUMNS
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

TRANSFERABLE SKILLS COLUMNS
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

SOFTWARE SKILLS COLUMNS
['O*NET-SOC Code', 'Title', 'Workplace Example', 'Element ID', 'Element Name', 'Hot Technology', 'In Demand']

In [7]:
# Show the actual essential skills for Business Intelligence Analysts

bi_skills = essential_skills[
    essential_skills["O*NET-SOC Code"] == occupation_code
].copy()

print("Number of essential-skill records:",
      len(bi_skills))

display(bi_skills)

Number of essential-skill records: 20

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
2680,15-2051.01,Business Intelligence Analysts,2.A.1.a,Reading Comprehension,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2024,Analyst
2681,15-2051.01,Business Intelligence Analysts,2.A.1.a,Reading Comprehension,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2024,Analyst
2682,15-2051.01,Business Intelligence Analysts,2.A.1.b,Active Listening,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2683,15-2051.01,Business Intelligence Analysts,2.A.1.b,Active Listening,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
2684,15-2051.01,Business Intelligence Analysts,2.A.1.c,Writing,IM,Importance,3.75,8,0.1637,3.4292,4.0708,N,NaN,08/2024,Analyst
2685,15-2051.01,Business Intelligence Analysts,2.A.1.c,Writing,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
2686,15-2051.01,Business Intelligence Analysts,2.A.1.d,Speaking,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2687,15-2051.01,Business Intelligence Analysts,2.A.1.d,Speaking,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
2688,15-2051.01,Business Intelligence Analysts,2.A.1.e,Mathematics,IM,Importance,3.50,8,0.1890,3.1296,3.8704,N,NaN,08/2024,Analyst
2689,15-2051.01,Business Intelligence Analysts,2.A.1.e,Mathematics,LV,Level,3.88,8,0.2266,3.4309,4.3191,N,N,08/2024,Analyst
2690,15-2051.01,Business Intelligence Analysts,2.A.1.f,Science,IM,Importance,1.62,8,0.1830,1.2664,1.9836,N,NaN,08/2024,Analyst
2691,15-2051.01,Business Intelligence Analysts,2.A.1.f,Science,LV,Level,0.75,8,0.2500,0.2600,1.2400,N,N,08/2024,Analyst
2692,15-2051.01,Business Intelligence Analysts,2.A.2.a,Critical Thinking,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2693,15-2051.01,Business Intelligence Analysts,2.A.2.a,Critical Thinking,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2024,Analyst
2694,15-2051.01,Business Intelligence Analysts,2.A.2.b,Active Learning,IM,Importance,3.88,8,0.1250,3.6300,4.1200,N,NaN,08/2024,Analyst
2695,15-2051.01,Business Intelligence Analysts,2.A.2.b,Active Learning,LV,Level,4.12,8,0.1250,3.8800,4.3700,N,N,08/2024,Analyst
2696,15-2051.01,Business Intelligence Analysts,2.A.2.c,Learning Strategies,IM,Importance,3.00,8,0.0000,3.0000,3.0000,N,NaN,08/2024,Analyst
2697,15-2051.01,Business Intelligence Analysts,2.A.2.c,Learning Strategies,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
2698,15-2051.01,Business Intelligence Analysts,2.A.2.d,Monitoring,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
2699,15-2051.01,Business Intelligence Analysts,2.A.2.d,Monitoring,LV,Level,3.25,8,0.1637,2.9292,3.5708,N,N,08/2024,Analyst

In [8]:
# ============================================================
# STEP: CREATE CLEAN SKILL PROFILE FOR BUSINESS INTELLIGENCE
# ============================================================

# Keep only the columns we need
skill_profile = bi_skills[
    [
        "Element ID",
        "Element Name",
        "Scale Name",
        "Data Value",
        "N"
    ]
].copy()

# Separate Importance and Level
importance = skill_profile[
    skill_profile["Scale Name"] == "Importance"
][
    ["Element ID", "Element Name", "Data Value"]
].copy()

level = skill_profile[
    skill_profile["Scale Name"] == "Level"
][
    ["Element ID", "Element Name", "Data Value"]
].copy()

# Rename values
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Merge importance and required level
clean_skill_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Sort by importance
clean_skill_profile = clean_skill_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("Clean skill profile:")
print(f"Number of skills: {len(clean_skill_profile)}")

display(clean_skill_profile)

Clean skill profile:
Number of skills: 10

  Element ID           Element Name  Importance  Required_Level
0    2.A.1.a  Reading Comprehension        4.00            4.25
1    2.A.1.b       Active Listening        3.88            4.00
2    2.A.1.d               Speaking        3.88            4.00
3    2.A.2.a      Critical Thinking        3.88            4.25
4    2.A.2.b        Active Learning        3.88            4.12
5    2.A.1.c                Writing        3.75            4.00
6    2.A.1.e            Mathematics        3.50            3.88
7    2.A.2.d             Monitoring        3.12            3.25
8    2.A.2.c    Learning Strategies        3.00            3.00
9    2.A.1.f                Science        1.62            0.75

In [11]:
# ============================================================
# STEP: EXTRACT TECHNICAL SKILLS FOR OUR TARGET OCCUPATION
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET data folder
onet_dir = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

# Target occupation
target_code = "15-2051.01"

# Load software skills
software = pd.read_csv(
    onet_dir / "software_skills.csv",
    low_memory=False
)

# Load knowledge
knowledge = pd.read_csv(
    onet_dir / "knowledge.csv",
    low_memory=False
)

# Filter for our target occupation
software_bi = software[
    software["O*NET-SOC Code"].astype(str).str.strip() == target_code
].copy()

knowledge_bi = knowledge[
    knowledge["O*NET-SOC Code"].astype(str).str.strip() == target_code
].copy()

# Display results
print("SOFTWARE SKILLS")
print("=" * 60)
print(f"Number of records: {len(software_bi)}")
display(software_bi)

print("\nKNOWLEDGE")
print("=" * 60)
print(f"Number of records: {len(knowledge_bi)}")
display(knowledge_bi)

SOFTWARE SKILLS
============================================================
Number of records: 203

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
11952,15-2051.01,Business Intelligence Analysts,Actuate Eclipse BIRT,2.E.6.e,Data base reporting software,N,N
11953,15-2051.01,Business Intelligence Analysts,Adobe Acrobat,2.E.5.b,Document management software,Y,N
11954,15-2051.01,Business Intelligence Analysts,Adobe ActionScript,2.E.7.b,Development environment software,N,N
11955,15-2051.01,Business Intelligence Analysts,Adobe Dreamweaver,2.E.4.g,Web page creation and editing software,N,N
11956,15-2051.01,Business Intelligence Analysts,Advanced business application programming ABAP,2.E.7.e,Object or component oriented development software,N,N
...,...,...,...,...,...,...,...
12150,15-2051.01,Business Intelligence Analysts,UNIX Shell,2.E.13.c,Operating system software,Y,N
12151,15-2051.01,Business Intelligence Analysts,Veritas NetBackup,2.E.15.f,Backup or archival software,N,N
12152,15-2051.01,Business Intelligence Analysts,Virtual private networking VPN software,2.E.14.c,Network security and virtual private network V...,N,N
12153,15-2051.01,Business Intelligence Analysts,Wireshark,2.E.11.a,Network monitoring software,N,N
12154,15-2051.01,Business Intelligence Analysts,YouTube,2.E.4.c,Video creation and editing software,N,N

KNOWLEDGE
============================================================
Number of records: 66

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
8844,15-2051.01,Business Intelligence Analysts,2.C.1.a,Administration and Management,IM,Importance,3.14,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8845,15-2051.01,Business Intelligence Analysts,2.C.1.a,Administration and Management,LV,Level,4.14,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8846,15-2051.01,Business Intelligence Analysts,2.C.1.b,Administrative,IM,Importance,2.43,21.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8847,15-2051.01,Business Intelligence Analysts,2.C.1.b,Administrative,LV,Level,3.64,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8848,15-2051.01,Business Intelligence Analysts,2.C.1.c,Economics and Accounting,IM,Importance,3.00,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8905,15-2051.01,Business Intelligence Analysts,2.C.9.a,Telecommunications,LV,Level,1.14,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8906,15-2051.01,Business Intelligence Analysts,2.C.9.b,Communications and Media,IM,Importance,2.59,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8907,15-2051.01,Business Intelligence Analysts,2.C.9.b,Communications and Media,LV,Level,2.95,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
8908,15-2051.01,Business Intelligence Analysts,2.C.10,Transportation,IM,Importance,1.18,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
8909,15-2051.01,Business Intelligence Analysts,2.C.10,Transportation,LV,Level,0.55,22.0,NaN,NaN,NaN,NaN,Y,08/2024,Occupational Expert

In [12]:
# ============================================================
# STEP: CREATE CLEAN KNOWLEDGE PROFILE
# ============================================================

# Keep only the useful columns
knowledge_profile = knowledge_bi[
    [
        "Element ID",
        "Element Name",
        "Scale Name",
        "Data Value"
    ]
].copy()

# Separate Importance and Level
knowledge_importance = knowledge_profile[
    knowledge_profile["Scale Name"] == "Importance"
][
    ["Element ID", "Element Name", "Data Value"]
].copy()

knowledge_level = knowledge_profile[
    knowledge_profile["Scale Name"] == "Level"
][
    ["Element ID", "Element Name", "Data Value"]
].copy()

# Rename columns
knowledge_importance = knowledge_importance.rename(
    columns={"Data Value": "Importance"}
)

knowledge_level = knowledge_level.rename(
    columns={"Data Value": "Required_Level"}
)

# Merge Importance + Level
clean_knowledge_profile = knowledge_importance.merge(
    knowledge_level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Sort by importance
clean_knowledge_profile = clean_knowledge_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("CLEAN KNOWLEDGE PROFILE")
print("=" * 60)
print(f"Number of knowledge areas: {len(clean_knowledge_profile)}")

display(clean_knowledge_profile)

CLEAN KNOWLEDGE PROFILE
============================================================
Number of knowledge areas: 33

   Element ID                   Element Name  Importance  Required_Level
0     2.C.3.a      Computers and Electronics        4.29            5.41
1     2.C.4.a                    Mathematics        3.82            4.67
2     2.C.7.a               English Language        3.77            4.41
3     2.C.1.a  Administration and Management        3.14            4.14
4     2.C.1.e  Customer and Personal Service        3.10            3.76
5     2.C.1.c       Economics and Accounting        3.00            3.59
6     2.C.9.b       Communications and Media        2.59            2.95
7       2.C.6         Education and Training        2.50            3.32
8     2.C.1.d            Sales and Marketing        2.45            3.14
9     2.C.3.c                         Design        2.43            2.50
10    2.C.1.b                 Administrative        2.43            3.64
11    2.C.3.b     Engineering and Technology        2.36            2.77
12    2.C.4.f     Sociology and Anthropology        2.23            2.59
13    2.C.4.g                      Geography        2.23            3.45
14    2.C.4.e                     Psychology        2.18            2.41
15    2.C.8.b             Law and Government        2.14            2.36
16    2.C.1.f  Personnel and Human Resources        1.91            2.23
17    2.C.2.a      Production and Processing        1.75            1.57
18    2.C.7.d         History and Archeology        1.73            1.77
19    2.C.9.a             Telecommunications        1.55            1.14
20    2.C.8.a     Public Safety and Security        1.55            1.00
21    2.C.7.c                      Fine Arts        1.50            1.00
22    2.C.7.e        Philosophy and Theology        1.45            1.23
23    2.C.7.b               Foreign Language        1.36            0.77
24    2.C.5.a         Medicine and Dentistry        1.18            0.45
25    2.C.5.b         Therapy and Counseling        1.18            0.32
26     2.C.10                 Transportation        1.18            0.55
27    2.C.3.d      Building and Construction        1.14            0.45
28    2.C.2.b                Food Production        1.14            0.55
29    2.C.3.e                     Mechanical        1.14            0.32
30    2.C.4.d                        Biology        1.09            0.36
31    2.C.4.b                        Physics        1.09            0.27
32    2.C.4.c                      Chemistry        1.09            0.27

In [13]:
# ============================================================
# STEP: CREATE CLEAN SOFTWARE SKILL PROFILE
# ============================================================

# Make a copy
software_profile = software_bi.copy()

# Keep the important columns
software_profile = software_profile[
    [
        "Element ID",
        "Element Name",
        "Hot Technology",
        "In Demand"
    ]
].copy()

# Remove duplicate software skills
software_profile = software_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Remove rows without a skill name
software_profile = software_profile.dropna(
    subset=["Element Name"]
)

# Reset index
software_profile = software_profile.reset_index(drop=True)

print("CLEAN SOFTWARE SKILL PROFILE")
print("=" * 60)
print(f"Number of software skills: {len(software_profile)}")

display(software_profile)

CLEAN SOFTWARE SKILL PROFILE
============================================================
Number of software skills: 51

,Element ID,Element Name,Hot Technology,In Demand
0,2.E.6.e,Data base reporting software,N,N
1,2.E.5.b,Document management software,Y,N
2,2.E.7.b,Development environment software,N,N
3,2.E.4.g,Web page creation and editing software,N,N
4,2.E.7.e,Object or component oriented development software,N,N
5,2.E.6.f,Data base user interface and query software,N,N
6,2.E.7.h,Web platform development software,Y,N
7,2.E.6.m,Business intelligence and data analysis software,Y,N
8,2.E.6.d,Data base management system software,Y,N
9,2.E.6.k,Portal server software,N,N
10,2.E.1.e,Project management software,Y,N
11,2.E.5.a,Content workflow software,Y,N
12,2.E.13.c,Operating system software,Y,N
13,2.E.6.c,Customer relationship management CRM software,N,N
14,2.E.12.a,Access software,N,N
15,2.E.6.l,Transaction server software,N,N
16,2.E.6.i,Metadata management software,N,N
17,2.E.6.g,Data mining software,N,N
18,2.E.2.d,Financial analysis software,N,N
19,2.E.10.b,Desktop communications software,N,N
20,2.E.9.i,Medical software,Y,N
21,2.E.8.h,Geographic information system,Y,N
22,2.E.7.c,Enterprise application integration software,Y,N
23,2.E.2.a,Accounting software,N,N
24,2.E.5.c,File versioning software,Y,N
25,2.E.10.a,Application server software,Y,N
26,2.E.1.l,Sales and marketing software,N,N
27,2.E.4.d,Word processing software,Y,N
28,2.E.4.f,Presentation software,N,N
29,2.E.7.f,Program testing software,N,N
30,2.E.6.j,Object oriented data base management software,Y,N
31,2.E.1.c,Human resources software,N,N
32,2.E.12.b,Communications server software,N,N
33,2.E.16.a,Electronic mail software,N,N
34,2.E.17.a,Enterprise system management software,N,N
35,2.E.9.d,Analytical or scientific software,Y,N
36,2.E.11.e,Cloud-based management software,N,N
37,2.E.6.h,Information retrieval or search software,N,N
38,2.E.14.d,Transaction security and virus protection soft...,N,N
39,2.E.2.b,Enterprise resource planning ERP software,N,N
40,2.E.4.i,Spreadsheet software,Y,Y
41,2.E.1.k,Office suite software,Y,Y
42,2.E.4.k,Desktop publishing software,N,N
43,2.E.1.p,Process mapping and design software,Y,N
44,2.E.11.a,Network monitoring software,N,N
45,2.E.9.c,Computer aided design CAD software,N,N
46,2.E.7.d,Graphical user interface development software,N,N
47,2.E.7.g,Requirements analysis and system architecture ...,N,N
48,2.E.15.f,Backup or archival software,N,N
49,2.E.14.c,Network security and virtual private network V...,N,N
50,2.E.4.c,Video creation and editing software,N,N

In [14]:
# ============================================================
# STEP: CREATE CLEAN ESSENTIAL SKILL PROFILE
# ============================================================

# Start with the essential skills for our target occupation
essential = essential_skills_bi.copy()

# Separate Importance and Level records
importance = essential[
    essential["Scale Name"].astype(str).str.strip().str.lower() == "importance"
].copy()

level = essential[
    essential["Scale Name"].astype(str).str.strip().str.lower() == "level"
].copy()

# Rename Data Value
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Keep only the columns we need
importance = importance[
    ["Element ID", "Element Name", "Importance"]
]

level = level[
    ["Element ID", "Element Name", "Required_Level"]
]

# Merge Importance + Required Level
clean_essential_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Remove duplicates
clean_essential_profile = clean_essential_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Sort by importance
clean_essential_profile = clean_essential_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("CLEAN ESSENTIAL SKILL PROFILE")
print("=" * 60)
print(f"Number of essential skills: {len(clean_essential_profile)}")

display(clean_essential_profile)

NameError: name 'essential_skills_bi' is not defined

In [17]:
# ============================================================
# STEP: CREATE CLEAN ESSENTIAL SKILL PROFILE
# ============================================================

# Target occupation
target_code = "15-2051.01"

# Load essential skills data
essential = pd.read_csv(
    ONET_DIR / "essential_skills.csv",
    low_memory=False
)

# Filter for Business Intelligence Analysts
essential_bi = essential[
    essential["O*NET-SOC Code"].astype(str).str.strip() == target_code
].copy()

print("Essential skills records found:", len(essential_bi))

# Separate Importance and Level records
importance = essential_bi[
    essential_bi["Scale Name"].astype(str).str.strip().str.lower() == "importance"
].copy()

level = essential_bi[
    essential_bi["Scale Name"].astype(str).str.strip().str.lower() == "level"
].copy()

# Rename Data Value
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Keep only the columns we need
importance = importance[
    ["Element ID", "Element Name", "Importance"]
]

level = level[
    ["Element ID", "Element Name", "Required_Level"]
]

# Merge Importance + Required Level
clean_essential_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Remove duplicates
clean_essential_profile = clean_essential_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Sort by importance
clean_essential_profile = clean_essential_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("\nCLEAN ESSENTIAL SKILL PROFILE")
print("=" * 60)
print(f"Number of essential skills: {len(clean_essential_profile)}")

display(clean_essential_profile)

Essential skills records found: 20

CLEAN ESSENTIAL SKILL PROFILE
============================================================
Number of essential skills: 10

  Element ID           Element Name  Importance  Required_Level
0    2.A.1.a  Reading Comprehension        4.00            4.25
1    2.A.1.b       Active Listening        3.88            4.00
2    2.A.1.d               Speaking        3.88            4.00
3    2.A.2.a      Critical Thinking        3.88            4.25
4    2.A.2.b        Active Learning        3.88            4.12
5    2.A.1.c                Writing        3.75            4.00
6    2.A.1.e            Mathematics        3.50            3.88
7    2.A.2.d             Monitoring        3.12            3.25
8    2.A.2.c    Learning Strategies        3.00            3.00
9    2.A.1.f                Science        1.62            0.75

In [16]:
# ============================================================
# FIX: DEFINE O*NET DATA DIRECTORY
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET data location
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

# Check that the directory exists
print("O*NET directory:", ONET_DIR)
print("Directory exists:", ONET_DIR.exists())

# ============================================================
# LOAD ESSENTIAL SKILLS
# ============================================================

target_code = "15-2051.01"

essential = pd.read_csv(
    ONET_DIR / "essential_skills.csv",
    low_memory=False
)

# Filter Business Intelligence Analysts
essential_bi = essential[
    essential["O*NET-SOC Code"].astype(str).str.strip() == target_code
].copy()

print("\nEssential skills records found:", len(essential_bi))

# ============================================================
# SEPARATE IMPORTANCE AND REQUIRED LEVEL
# ============================================================

importance = essential_bi[
    essential_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "importance"
].copy()

level = essential_bi[
    essential_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "level"
].copy()

# Rename values
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Keep only relevant columns
importance = importance[
    ["Element ID", "Element Name", "Importance"]
]

level = level[
    ["Element ID", "Element Name", "Required_Level"]
]

# ============================================================
# MERGE
# ============================================================

clean_essential_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Remove duplicates
clean_essential_profile = clean_essential_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Sort by importance
clean_essential_profile = clean_essential_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

# ============================================================
# DISPLAY RESULT
# ============================================================

print("\nCLEAN ESSENTIAL SKILL PROFILE")
print("=" * 60)
print(
    f"Number of essential skills: "
    f"{len(clean_essential_profile)}"
)

display(clean_essential_profile)

O*NET directory: /home/Student/career-intelligence/data/raw/onet/db_31_0_csv
Directory exists: True

Essential skills records found: 20

CLEAN ESSENTIAL SKILL PROFILE
============================================================
Number of essential skills: 10

  Element ID           Element Name  Importance  Required_Level
0    2.A.1.a  Reading Comprehension        4.00            4.25
1    2.A.1.b       Active Listening        3.88            4.00
2    2.A.1.d               Speaking        3.88            4.00
3    2.A.2.a      Critical Thinking        3.88            4.25
4    2.A.2.b        Active Learning        3.88            4.12
5    2.A.1.c                Writing        3.75            4.00
6    2.A.1.e            Mathematics        3.50            3.88
7    2.A.2.d             Monitoring        3.12            3.25
8    2.A.2.c    Learning Strategies        3.00            3.00
9    2.A.1.f                Science        1.62            0.75

In [1]:
# ============================================================
# STEP: CREATE CLEAN TRANSFERABLE SKILL PROFILE
# ============================================================

# Load transferable skills
transferable = pd.read_csv(
    ONET_DIR / "transferable_skills.csv",
    low_memory=False
)

# Filter for our target occupation
transferable_bi = transferable[
    transferable["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("Transferable skill records found:", len(transferable_bi))

# Separate Importance and Level
importance = transferable_bi[
    transferable_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "importance"
].copy()

level = transferable_bi[
    transferable_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "level"
].copy()

# Rename Data Value
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Keep relevant columns
importance = importance[
    ["Element ID", "Element Name", "Importance"]
]

level = level[
    ["Element ID", "Element Name", "Required_Level"]
]

# Merge importance + required level
clean_transferable_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Remove duplicates
clean_transferable_profile = clean_transferable_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Sort by importance
clean_transferable_profile = clean_transferable_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("\nCLEAN TRANSFERABLE SKILL PROFILE")
print("=" * 60)
print(
    f"Number of transferable skills: "
    f"{len(clean_transferable_profile)}"
)

display(clean_transferable_profile)

NameError: name 'pd' is not defined

In [2]:
# ============================================================
# STEP: CREATE CLEAN TRANSFERABLE SKILL PROFILE
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET data directory
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

# Target occupation: Business Intelligence Analysts
target_code = "15-2051.01"

# Check directory
print("O*NET directory:", ONET_DIR)
print("Directory exists:", ONET_DIR.exists())

# ============================================================
# LOAD TRANSFERABLE SKILLS
# ============================================================

transferable = pd.read_csv(
    ONET_DIR / "transferable_skills.csv",
    low_memory=False
)

# Filter for Business Intelligence Analysts
transferable_bi = transferable[
    transferable["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("\nTransferable skill records found:", len(transferable_bi))

# ============================================================
# SEPARATE IMPORTANCE AND REQUIRED LEVEL
# ============================================================

importance = transferable_bi[
    transferable_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "importance"
].copy()

level = transferable_bi[
    transferable_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "level"
].copy()

# Rename Data Value
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Keep relevant columns
importance = importance[
    ["Element ID", "Element Name", "Importance"]
]

level = level[
    ["Element ID", "Element Name", "Required_Level"]
]

# ============================================================
# MERGE IMPORTANCE + REQUIRED LEVEL
# ============================================================

clean_transferable_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Remove duplicate skills
clean_transferable_profile = clean_transferable_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Sort by importance
clean_transferable_profile = clean_transferable_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

# ============================================================
# DISPLAY RESULT
# ============================================================

print("\nCLEAN TRANSFERABLE SKILL PROFILE")
print("=" * 60)
print(
    f"Number of transferable skills: "
    f"{len(clean_transferable_profile)}"
)

display(clean_transferable_profile)

O*NET directory: /home/Student/career-intelligence/data/raw/onet/db_31_0_csv
Directory exists: True

Transferable skill records found: 50

CLEAN TRANSFERABLE SKILL PROFILE
============================================================
Number of transferable skills: 25

   Element ID                       Element Name  Importance  Required_Level
0     2.B.4.e       Judgment and Decision Making        3.62            4.00
1     2.B.2.i            Complex Problem Solving        3.38            3.75
2     2.B.4.h                 Systems Evaluation        3.12            3.75
3     2.B.5.a                    Time Management        3.12            3.00
4     2.B.4.g                   Systems Analysis        3.12            3.75
5     2.B.1.e                        Instructing        3.00            3.00
6     2.B.1.b                       Coordination        3.00            3.00
7     2.B.1.a              Social Perceptiveness        2.88            2.88
8     2.B.1.c                         Persuasion        2.88            3.00
9     2.B.1.f                Service Orientation        2.88            2.88
10    2.B.3.e                        Programming        2.50            2.50
11    2.B.1.d                        Negotiation        2.50            2.88
12    2.B.5.d  Management of Personnel Resources        2.12            2.00
13    2.B.3.m           Quality Control Analysis        2.00            1.50
14    2.B.3.a                Operations Analysis        1.88            1.62
15    2.B.5.b  Management of Financial Resources        1.88            1.75
16    2.B.3.g              Operations Monitoring        1.75            1.12
17    2.B.5.c   Management of Material Resources        1.75            1.25
18    2.B.3.b                  Technology Design        1.62            0.88
19    2.B.3.h              Operation and Control        1.38            0.38
20    2.B.3.l                          Repairing        1.00            0.00
21    2.B.3.d                       Installation        1.00            0.00
22    2.B.3.k                    Troubleshooting        1.00            0.00
23    2.B.3.j              Equipment Maintenance        1.00            0.00
24    2.B.3.c                Equipment Selection        1.00            0.00

In [3]:
# ============================================================
# STEP: CREATE CLEAN TRANSFERABLE SKILL PROFILE
# ============================================================

import pandas as pd

# Target occupation
target_code = "15-2051.01"

# Load transferable skills data
transferable = pd.read_csv(
    ONET_DIR / "transferable_skills.csv",
    low_memory=False
)

# Filter for Business Intelligence Analysts
transferable_bi = transferable[
    transferable["O*NET-SOC Code"].astype(str).str.strip() == target_code
].copy()

print("TRANSFERABLE SKILLS")
print("=" * 60)
print(f"Number of records: {len(transferable_bi)}")

display(transferable_bi)

TRANSFERABLE SKILLS
============================================================
Number of records: 50

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
6700,15-2051.01,Business Intelligence Analysts,2.B.1.a,Social Perceptiveness,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2024,Analyst
6701,15-2051.01,Business Intelligence Analysts,2.B.1.a,Social Perceptiveness,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2024,Analyst
6702,15-2051.01,Business Intelligence Analysts,2.B.1.b,Coordination,IM,Importance,3.00,8,0.0000,3.0000,3.0000,N,NaN,08/2024,Analyst
6703,15-2051.01,Business Intelligence Analysts,2.B.1.b,Coordination,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
6704,15-2051.01,Business Intelligence Analysts,2.B.1.c,Persuasion,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2024,Analyst
6705,15-2051.01,Business Intelligence Analysts,2.B.1.c,Persuasion,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
6706,15-2051.01,Business Intelligence Analysts,2.B.1.d,Negotiation,IM,Importance,2.50,8,0.1890,2.1296,2.8704,N,NaN,08/2024,Analyst
6707,15-2051.01,Business Intelligence Analysts,2.B.1.d,Negotiation,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2024,Analyst
6708,15-2051.01,Business Intelligence Analysts,2.B.1.e,Instructing,IM,Importance,3.00,8,0.0000,3.0000,3.0000,N,NaN,08/2024,Analyst
6709,15-2051.01,Business Intelligence Analysts,2.B.1.e,Instructing,LV,Level,3.00,8,0.0000,3.0000,3.0000,N,N,08/2024,Analyst
6710,15-2051.01,Business Intelligence Analysts,2.B.1.f,Service Orientation,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2024,Analyst
6711,15-2051.01,Business Intelligence Analysts,2.B.1.f,Service Orientation,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2024,Analyst
6712,15-2051.01,Business Intelligence Analysts,2.B.2.i,Complex Problem Solving,IM,Importance,3.38,8,0.1830,3.0164,3.7336,N,NaN,08/2024,Analyst
6713,15-2051.01,Business Intelligence Analysts,2.B.2.i,Complex Problem Solving,LV,Level,3.75,8,0.1637,3.4292,4.0708,N,N,08/2024,Analyst
6714,15-2051.01,Business Intelligence Analysts,2.B.3.a,Operations Analysis,IM,Importance,1.88,8,0.2266,1.4309,2.3191,N,NaN,08/2024,Analyst
6715,15-2051.01,Business Intelligence Analysts,2.B.3.a,Operations Analysis,LV,Level,1.62,8,0.3750,0.8900,2.3600,N,N,08/2024,Analyst
6716,15-2051.01,Business Intelligence Analysts,2.B.3.b,Technology Design,IM,Importance,1.62,8,0.1830,1.2664,1.9836,N,NaN,08/2024,Analyst
6717,15-2051.01,Business Intelligence Analysts,2.B.3.b,Technology Design,LV,Level,0.88,8,0.2950,0.2967,1.4533,N,N,08/2024,Analyst
6718,15-2051.01,Business Intelligence Analysts,2.B.3.c,Equipment Selection,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6719,15-2051.01,Business Intelligence Analysts,2.B.3.c,Equipment Selection,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6720,15-2051.01,Business Intelligence Analysts,2.B.3.d,Installation,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6721,15-2051.01,Business Intelligence Analysts,2.B.3.d,Installation,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6722,15-2051.01,Business Intelligence Analysts,2.B.3.e,Programming,IM,Importance,2.50,8,0.1890,2.1296,2.8704,N,NaN,08/2024,Analyst
6723,15-2051.01,Business Intelligence Analysts,2.B.3.e,Programming,LV,Level,2.50,8,0.1890,2.1296,2.8704,N,N,08/2024,Analyst
6724,15-2051.01,Business Intelligence Analysts,2.B.3.g,Operations Monitoring,IM,Importance,1.75,8,0.1637,1.4292,2.0708,N,NaN,08/2024,Analyst
6725,15-2051.01,Business Intelligence Analysts,2.B.3.g,Operations Monitoring,LV,Level,1.12,8,0.2950,0.5467,1.7033,N,N,08/2024,Analyst
6726,15-2051.01,Business Intelligence Analysts,2.B.3.h,Operation and Control,IM,Importance,1.38,8,0.1830,1.0164,1.7336,N,NaN,08/2024,Analyst
6727,15-2051.01,Business Intelligence Analysts,2.B.3.h,Operation and Control,LV,Level,0.38,8,0.1830,0.0164,0.7336,N,N,08/2024,Analyst
6728,15-2051.01,Business Intelligence Analysts,2.B.3.j,Equipment Maintenance,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6729,15-2051.01,Business Intelligence Analysts,2.B.3.j,Equipment Maintenance,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6730,15-2051.01,Business Intelligence Analysts,2.B.3.k,Troubleshooting,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6731,15-2051.01,Business Intelligence Analysts,2.B.3.k,Troubleshooting,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6732,15-2051.01,Business Intelligence Analysts,2.B.3.l,Repairing,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2024,Analyst
6733,15-2051.01,Business Intelligence Analysts,2.B.3.l,Repairing,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2024,Analyst
6734,15-2051.01,Business Intelligence Analysts,2.B.3.m,Quality Control Analysis,IM,Importance,2.00,8,0.1890,1.6296,2.3704,N,NaN,08/2024,Analyst
6735,15-2051.01,Business Intelligence Analysts,2.B.3.m,Quality Control Analysis,LV,Level,1.50,8,0.3273,0.8584,2.1416,N,N,08/2024,Analyst
6736,15-2051.01,Business Intelligence Analysts,2.B.4.e,Judgment and Decision Making,IM,Importance,3.62,8,0.1830,3.2664,3.9836,N,NaN,08/2024,Analyst
6737,15-2051.01,Business Intelligence Analysts,2.B.4.e,Judgment and Decision Making,LV,Level,4.00,8,0.0000,4.0000,4.0000,N,N,08/2024,Analyst
6738,15-2051.01,Business Intelligence Analysts,2.B.4.g,Systems Analysis,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
6739,15-2051.01,Business Intelligence Analysts,2.B.4.g,Systems Analysis,LV,Level,3.75,8,0.1637,3.4292,4.0708,N,N,08/2024,Analyst
6740,15-2051.01,Business Intelligence Analysts,2.B.4.h,Systems Evaluation,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
6741,15-2051.01,Business Intelligence Analysts,2.B.4.h,Systems Evaluation,LV,Level,3.75,8,0.1637,3.4292,4.0708,N,N,08/2024,Analyst
6742,15-2051.01,Business Intelligence Analysts,2.B.5.a,Time Management,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2024,Analyst
6743,15-2051.01,Business Intelligence Analysts,2.B.5.a,Time Management,LV,Level,3.00,8,0.1890,2.6296,3.3704,N,N,08/2024,Analyst
6744,15-2051.01,Business Intelligence Analysts,2.B.5.b,Management of Financial Resources,IM,Importance,1.88,8,0.1250,1.6300,2.1200,N,NaN,08/2024,Analyst
6745,15-2051.01,Business Intelligence Analysts,2.B.5.b,Management of Financial Resources,LV,Level,1.75,8,0.2500,1.2600,2.2400,N,N,08/2024,Analyst
6746,15-2051.01,Business Intelligence Analysts,2.B.5.c,Management of Material Resources,IM,Importance,1.75,8,0.1637,1.4292,2.0708,N,NaN,08/2024,Analyst
6747,15-2051.01,Business Intelligence Analysts,2.B.5.c,Management of Material Resources,LV,Level,1.25,8,0.3134,0.6358,1.8642,N,N,08/2024,Analyst
6748,15-2051.01,Business Intelligence Analysts,2.B.5.d,Management of Personnel Resources,IM,Importance,2.12,8,0.1250,1.8800,2.3700,N,NaN,08/2024,Analyst
6749,15-2051.01,Business Intelligence Analysts,2.B.5.d,Management of Personnel Resources,LV,Level,2.00,8,0.1890,1.6296,2.3704,N,N,08/2024,Analyst

In [4]:
# ============================================================
# STEP: CREATE CLEAN TRANSFERABLE SKILL PROFILE
# ============================================================

# Start with the transferable skills for our target occupation
transferable = transferable_bi.copy()

# Separate Importance and Level records
importance = transferable[
    transferable["Scale Name"].astype(str).str.strip().str.lower() == "importance"
].copy()

level = transferable[
    transferable["Scale Name"].astype(str).str.strip().str.lower() == "level"
].copy()

# Rename Data Value
importance = importance.rename(
    columns={"Data Value": "Importance"}
)

level = level.rename(
    columns={"Data Value": "Required_Level"}
)

# Keep only the columns we need
importance = importance[
    ["Element ID", "Element Name", "Importance"]
]

level = level[
    ["Element ID", "Element Name", "Required_Level"]
]

# Merge Importance + Required Level
clean_transferable_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
)

# Remove duplicates
clean_transferable_profile = clean_transferable_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Sort by importance
clean_transferable_profile = clean_transferable_profile.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

# Display result
print("CLEAN TRANSFERABLE SKILL PROFILE")
print("=" * 60)
print(f"Number of transferable skills: {len(clean_transferable_profile)}")

display(clean_transferable_profile)

CLEAN TRANSFERABLE SKILL PROFILE
============================================================
Number of transferable skills: 25

   Element ID                       Element Name  Importance  Required_Level
0     2.B.4.e       Judgment and Decision Making        3.62            4.00
1     2.B.2.i            Complex Problem Solving        3.38            3.75
2     2.B.4.h                 Systems Evaluation        3.12            3.75
3     2.B.5.a                    Time Management        3.12            3.00
4     2.B.4.g                   Systems Analysis        3.12            3.75
5     2.B.1.e                        Instructing        3.00            3.00
6     2.B.1.b                       Coordination        3.00            3.00
7     2.B.1.a              Social Perceptiveness        2.88            2.88
8     2.B.1.c                         Persuasion        2.88            3.00
9     2.B.1.f                Service Orientation        2.88            2.88
10    2.B.3.e                        Programming        2.50            2.50
11    2.B.1.d                        Negotiation        2.50            2.88
12    2.B.5.d  Management of Personnel Resources        2.12            2.00
13    2.B.3.m           Quality Control Analysis        2.00            1.50
14    2.B.3.a                Operations Analysis        1.88            1.62
15    2.B.5.b  Management of Financial Resources        1.88            1.75
16    2.B.3.g              Operations Monitoring        1.75            1.12
17    2.B.5.c   Management of Material Resources        1.75            1.25
18    2.B.3.b                  Technology Design        1.62            0.88
19    2.B.3.h              Operation and Control        1.38            0.38
20    2.B.3.l                          Repairing        1.00            0.00
21    2.B.3.d                       Installation        1.00            0.00
22    2.B.3.k                    Troubleshooting        1.00            0.00
23    2.B.3.j              Equipment Maintenance        1.00            0.00
24    2.B.3.c                Equipment Selection        1.00            0.00

In [6]:
# ============================================================
# STEP: ANALYZE SOFTWARE SKILL SIGNALS
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET data directory
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

# Target occupation
target_code = "15-2051.01"

# Load software skills
software = pd.read_csv(
    ONET_DIR / "software_skills.csv",
    low_memory=False
)

# Filter Business Intelligence Analysts
software_bi = software[
    software["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("Raw software records:", len(software_bi))

# ============================================================
# CREATE CLEAN SOFTWARE PROFILE
# ============================================================

software_profile = software_bi[
    [
        "Element ID",
        "Element Name",
        "Hot Technology",
        "In Demand"
    ]
].copy()

# Remove duplicate software records
software_profile = software_profile.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Remove missing software names
software_profile = software_profile.dropna(
    subset=["Element Name"]
).reset_index(drop=True)

# ============================================================
# NORMALIZE INDICATORS
# ============================================================

for column in ["Hot Technology", "In Demand"]:
    software_profile[column] = (
        software_profile[column]
        .astype(str)
        .str.strip()
        .str.upper()
    )

print("\nCLEAN SOFTWARE PROFILE")
print("=" * 60)
print("Distinct software skills:", len(software_profile))

print("\nHot Technology:")
print(
    software_profile["Hot Technology"]
    .value_counts(dropna=False)
)

print("\nIn Demand:")
print(
    software_profile["In Demand"]
    .value_counts(dropna=False)
)

# ============================================================
# FIND SOFTWARE THAT IS BOTH HOT AND IN DEMAND
# ============================================================

both = software_profile[
    (software_profile["Hot Technology"] == "Y") &
    (software_profile["In Demand"] == "Y")
]

print("\nBoth Hot Technology AND In Demand:")
print(len(both))

display(both)

Raw software records: 203

CLEAN SOFTWARE PROFILE
============================================================
Distinct software skills: 51

Hot Technology:
Hot Technology
N    33
Y    18
Name: count, dtype: int64

In Demand:
In Demand
N    49
Y     2
Name: count, dtype: int64

Both Hot Technology AND In Demand:
2

   Element ID           Element Name Hot Technology In Demand
40    2.E.4.i   Spreadsheet software              Y         Y
41    2.E.1.k  Office suite software              Y         Y

In [7]:
print("HOT TECHNOLOGY")
print("=" * 50)
print(software_profile["Hot Technology"].value_counts(dropna=False))

print("\nIN DEMAND")
print("=" * 50)
print(software_profile["In Demand"].value_counts(dropna=False))

both = software_profile[
    (software_profile["Hot Technology"] == "Y") &
    (software_profile["In Demand"] == "Y")
]

print("\nBOTH HOT TECHNOLOGY AND IN DEMAND")
print("=" * 50)
print("Count:", len(both))

display(both)

HOT TECHNOLOGY
==================================================
Hot Technology
N    33
Y    18
Name: count, dtype: int64

IN DEMAND
==================================================
In Demand
N    49
Y     2
Name: count, dtype: int64

BOTH HOT TECHNOLOGY AND IN DEMAND
==================================================
Count: 2

   Element ID           Element Name Hot Technology In Demand
40    2.E.4.i   Spreadsheet software              Y         Y
41    2.E.1.k  Office suite software              Y         Y

In [8]:
# ============================================================
# STAGE 6 — EXPLORE WORK ACTIVITIES
# ============================================================

from pathlib import Path
import pandas as pd

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# Load work activities
work_activities = pd.read_csv(
    ONET_DIR / "work_activities.csv",
    low_memory=False
)

# Filter target occupation
work_bi = work_activities[
    work_activities["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("WORK ACTIVITIES")
print("=" * 60)
print("Raw records:", len(work_bi))

print("\nColumns:")
print(list(work_bi.columns))

display(work_bi.head(20))

WORK ACTIVITIES
============================================================
Raw records: 82

Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
10988,15-2051.01,Business Intelligence Analysts,4.A.1.a.1,Getting Information,IM,Importance,4.50,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
10989,15-2051.01,Business Intelligence Analysts,4.A.1.a.1,Getting Information,LV,Level,5.41,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
10990,15-2051.01,Business Intelligence Analysts,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,2.76,21.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
10991,15-2051.01,Business Intelligence Analysts,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",LV,Level,3.29,21.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
10992,15-2051.01,Business Intelligence Analysts,4.A.1.b.1,"Identifying Objects, Actions, and Events",IM,Importance,3.91,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
10993,15-2051.01,Business Intelligence Analysts,4.A.1.b.1,"Identifying Objects, Actions, and Events",LV,Level,4.73,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
10994,15-2051.01,Business Intelligence Analysts,4.A.1.b.2,"Inspecting Equipment, Structures, or Materials",IM,Importance,1.23,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
10995,15-2051.01,Business Intelligence Analysts,4.A.1.b.2,"Inspecting Equipment, Structures, or Materials",LV,Level,0.55,22.0,NaN,NaN,NaN,NaN,Y,08/2024,Occupational Expert
10996,15-2051.01,Business Intelligence Analysts,4.A.1.b.3,Estimating the Quantifiable Characteristics of...,IM,Importance,3.27,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
10997,15-2051.01,Business Intelligence Analysts,4.A.1.b.3,Estimating the Quantifiable Characteristics of...,LV,Level,3.82,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
10998,15-2051.01,Business Intelligence Analysts,4.A.2.a.1,"Judging the Qualities of Objects, Services, or...",IM,Importance,2.91,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
10999,15-2051.01,Business Intelligence Analysts,4.A.2.a.1,"Judging the Qualities of Objects, Services, or...",LV,Level,3.76,21.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
11000,15-2051.01,Business Intelligence Analysts,4.A.2.a.2,Processing Information,IM,Importance,4.64,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
11001,15-2051.01,Business Intelligence Analysts,4.A.2.a.2,Processing Information,LV,Level,5.73,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
11002,15-2051.01,Business Intelligence Analysts,4.A.2.a.3,Evaluating Information to Determine Compliance...,IM,Importance,3.24,21.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
11003,15-2051.01,Business Intelligence Analysts,4.A.2.a.3,Evaluating Information to Determine Compliance...,LV,Level,3.68,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
11004,15-2051.01,Business Intelligence Analysts,4.A.2.a.4,Analyzing Data or Information,IM,Importance,4.73,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
11005,15-2051.01,Business Intelligence Analysts,4.A.2.a.4,Analyzing Data or Information,LV,Level,6.09,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert
11006,15-2051.01,Business Intelligence Analysts,4.A.2.b.1,Making Decisions and Solving Problems,IM,Importance,3.82,22.0,NaN,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
11007,15-2051.01,Business Intelligence Analysts,4.A.2.b.1,Making Decisions and Solving Problems,LV,Level,4.59,22.0,NaN,NaN,NaN,NaN,N,08/2024,Occupational Expert

In [9]:
# ============================================================
# STAGE 7 — EXPLORE TASK STATEMENTS
# ============================================================

from pathlib import Path
import pandas as pd

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# Load task statements
tasks = pd.read_csv(
    ONET_DIR / "task_statements.csv",
    low_memory=False
)

# Filter target occupation
tasks_bi = tasks[
    tasks["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("TASK STATEMENTS")
print("=" * 60)
print("Raw records:", len(tasks_bi))

print("\nColumns:")
print(list(tasks_bi.columns))

display(tasks_bi.head(20))

TASK STATEMENTS
============================================================
Raw records: 17

Columns:
['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type', 'Incumbents Responding', 'Date', 'Domain Source']

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
2914,15-2051.01,Business Intelligence Analysts,16150,Generate standard or custom reports summarizin...,Core,22.0,08/2024,Occupational Expert
2915,15-2051.01,Business Intelligence Analysts,16139,Maintain or update business intelligence tools...,Core,22.0,08/2024,Occupational Expert
2916,15-2051.01,Business Intelligence Analysts,16140,Manage timely flow of business intelligence in...,Core,22.0,08/2024,Occupational Expert
2917,15-2051.01,Business Intelligence Analysts,16134,Provide technical support for existing reports...,Core,21.0,08/2024,Occupational Expert
2918,15-2051.01,Business Intelligence Analysts,16141,Identify and analyze industry or geographic tr...,Core,22.0,08/2024,Occupational Expert
2919,15-2051.01,Business Intelligence Analysts,16142,Document specifications for business intellige...,Core,22.0,08/2024,Occupational Expert
2920,15-2051.01,Business Intelligence Analysts,16144,"Create business intelligence tools or systems,...",Core,21.0,08/2024,Occupational Expert
2921,15-2051.01,Business Intelligence Analysts,16146,Collect business intelligence data from availa...,Core,22.0,08/2024,Occupational Expert
2922,15-2051.01,Business Intelligence Analysts,16143,"Disseminate information regarding tools, repor...",Core,21.0,08/2024,Occupational Expert
2923,15-2051.01,Business Intelligence Analysts,16145,Conduct or coordinate tests to ensure that int...,Core,22.0,08/2024,Occupational Expert
2924,15-2051.01,Business Intelligence Analysts,16149,Synthesize current business intelligence or tr...,Core,22.0,08/2024,Occupational Expert
2925,15-2051.01,Business Intelligence Analysts,16148,Analyze competitive market strategies through ...,Core,22.0,08/2024,Occupational Expert
2926,15-2051.01,Business Intelligence Analysts,16136,Identify or monitor current and potential cust...,Core,22.0,08/2024,Occupational Expert
2927,15-2051.01,Business Intelligence Analysts,16138,"Communicate with customers, competitors, suppl...",Core,22.0,08/2024,Occupational Expert
2928,15-2051.01,Business Intelligence Analysts,16135,"Maintain library of model documents, templates...",Core,22.0,08/2024,Occupational Expert
2929,15-2051.01,Business Intelligence Analysts,16137,Create or review technical design documentatio...,Core,22.0,08/2024,Occupational Expert
2930,15-2051.01,Business Intelligence Analysts,16147,Analyze technology trends to identify markets ...,Core,22.0,08/2024,Occupational Expert

In [10]:
# ============================================================
# STEP 7.1 — CLEAN TASK STATEMENTS
# ============================================================

# Work with our filtered task data
clean_tasks = tasks_bi.copy()

# Show the available columns first
print("Available columns:")
print(list(clean_tasks.columns))

# Remove completely empty columns
clean_tasks = clean_tasks.dropna(axis=1, how="all")

# Remove duplicate task records
clean_tasks = clean_tasks.drop_duplicates()

# Find the task-description column automatically
task_columns = [
    col for col in clean_tasks.columns
    if "task" in col.lower() and "id" not in col.lower()
]

print("\nPossible task description columns:")
print(task_columns)

# Display the cleaned task records
print("\nClean task records:", len(clean_tasks))

display(clean_tasks)

Available columns:
['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type', 'Incumbents Responding', 'Date', 'Domain Source']

Possible task description columns:
['Task', 'Task Type']

Clean task records: 17

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
2914,15-2051.01,Business Intelligence Analysts,16150,Generate standard or custom reports summarizin...,Core,22.0,08/2024,Occupational Expert
2915,15-2051.01,Business Intelligence Analysts,16139,Maintain or update business intelligence tools...,Core,22.0,08/2024,Occupational Expert
2916,15-2051.01,Business Intelligence Analysts,16140,Manage timely flow of business intelligence in...,Core,22.0,08/2024,Occupational Expert
2917,15-2051.01,Business Intelligence Analysts,16134,Provide technical support for existing reports...,Core,21.0,08/2024,Occupational Expert
2918,15-2051.01,Business Intelligence Analysts,16141,Identify and analyze industry or geographic tr...,Core,22.0,08/2024,Occupational Expert
2919,15-2051.01,Business Intelligence Analysts,16142,Document specifications for business intellige...,Core,22.0,08/2024,Occupational Expert
2920,15-2051.01,Business Intelligence Analysts,16144,"Create business intelligence tools or systems,...",Core,21.0,08/2024,Occupational Expert
2921,15-2051.01,Business Intelligence Analysts,16146,Collect business intelligence data from availa...,Core,22.0,08/2024,Occupational Expert
2922,15-2051.01,Business Intelligence Analysts,16143,"Disseminate information regarding tools, repor...",Core,21.0,08/2024,Occupational Expert
2923,15-2051.01,Business Intelligence Analysts,16145,Conduct or coordinate tests to ensure that int...,Core,22.0,08/2024,Occupational Expert
2924,15-2051.01,Business Intelligence Analysts,16149,Synthesize current business intelligence or tr...,Core,22.0,08/2024,Occupational Expert
2925,15-2051.01,Business Intelligence Analysts,16148,Analyze competitive market strategies through ...,Core,22.0,08/2024,Occupational Expert
2926,15-2051.01,Business Intelligence Analysts,16136,Identify or monitor current and potential cust...,Core,22.0,08/2024,Occupational Expert
2927,15-2051.01,Business Intelligence Analysts,16138,"Communicate with customers, competitors, suppl...",Core,22.0,08/2024,Occupational Expert
2928,15-2051.01,Business Intelligence Analysts,16135,"Maintain library of model documents, templates...",Core,22.0,08/2024,Occupational Expert
2929,15-2051.01,Business Intelligence Analysts,16137,Create or review technical design documentatio...,Core,22.0,08/2024,Occupational Expert
2930,15-2051.01,Business Intelligence Analysts,16147,Analyze technology trends to identify markets ...,Core,22.0,08/2024,Occupational Expert

In [11]:
# ============================================================
# STAGE 8 — EXPLORE EDUCATION & EXPERIENCE REQUIREMENTS
# ============================================================

from pathlib import Path
import pandas as pd

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# ------------------------------------------------------------
# EDUCATION
# ------------------------------------------------------------

education = pd.read_csv(
    ONET_DIR / "education.csv",
    low_memory=False
)

education_bi = education[
    education["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("EDUCATION")
print("=" * 60)
print("Raw records:", len(education_bi))
print("Columns:")
print(list(education_bi.columns))

display(education_bi.head(20))


# ------------------------------------------------------------
# TRAINING & EXPERIENCE
# ------------------------------------------------------------

training = pd.read_csv(
    ONET_DIR / "training_and_experience.csv",
    low_memory=False
)

training_bi = training[
    training["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("\nTRAINING AND EXPERIENCE")
print("=" * 60)
print("Raw records:", len(training_bi))
print("Columns:")
print(list(training_bi.columns))

display(training_bi.head(20))

EDUCATION
============================================================
Raw records: 13
Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
1681,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),1.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1682,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),2.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1683,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),3.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1684,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),4.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1685,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),5.0,4.55,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1686,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),6.0,68.18,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1687,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),7.0,4.55,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1688,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),8.0,22.73,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1689,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),9.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1690,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),10.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1691,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),11.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1692,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),12.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
1693,15-2051.01,Business Intelligence Analysts,2.D.4.a,Job-Related Professional Certification,IM,Importance,NaN,1.82,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert

TRAINING AND EXPERIENCE
============================================================
Raw records: 30
Columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
3908,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),1.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3909,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),2.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3910,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),3.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3911,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),4.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3912,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),5.0,9.09,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3913,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),6.0,13.64,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3914,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),7.0,36.36,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3915,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),8.0,31.82,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3916,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),9.0,9.09,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3917,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),10.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3918,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),11.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3919,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),1.0,27.27,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3920,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),2.0,13.64,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3921,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),3.0,13.64,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3922,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),4.0,13.64,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3923,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),5.0,13.64,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3924,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),6.0,13.64,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3925,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),7.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3926,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),8.0,4.55,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert
3927,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),9.0,0.00,22,NaN,NaN,NaN,NaN,08/2024,Occupational Expert

In [12]:
# ============================================================
# STAGE 9 — CREATE STANDARDIZED OCCUPATION PROFILE
# ============================================================

import pandas as pd
from pathlib import Path

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# Load occupation data
occupation_data = pd.read_csv(
    ONET_DIR / "occupation_data.csv",
    low_memory=False
)

# Find our target occupation
occupation_bi = occupation_data[
    occupation_data["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("TARGET OCCUPATION")
print("=" * 60)

display(occupation_bi)

TARGET OCCUPATION
============================================================

,O*NET-SOC Code,Title,Description
143,15-2051.01,Business Intelligence Analysts,Produce financial and market intelligence by q...

In [14]:
# ============================================================
# STAGE 9.1 — BUILD MASTER SKILL DATASET
# SELF-CONTAINED VERSION
# ============================================================

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------
# 1. SETUP
# ------------------------------------------------------------

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# ------------------------------------------------------------
# 2. LOAD OCCUPATION DATA
# ------------------------------------------------------------

occupation_data = pd.read_csv(
    ONET_DIR / "occupation_data.csv",
    low_memory=False
)

occupation_bi = occupation_data[
    occupation_data["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

occupation_title = occupation_bi["Title"].iloc[0]

print("Occupation:", occupation_title)

# ------------------------------------------------------------
# 3. LOAD ESSENTIAL SKILLS
# ------------------------------------------------------------

essential = pd.read_csv(
    ONET_DIR / "essential_skills.csv",
    low_memory=False
)

essential_bi = essential[
    essential["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

importance = essential_bi[
    essential_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "importance"
].copy()

level = essential_bi[
    essential_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "level"
].copy()

importance = importance.rename(
    columns={"Data Value": "importance"}
)

level = level.rename(
    columns={"Data Value": "required_level"}
)

importance = importance[
    ["Element ID", "Element Name", "importance"]
]

level = level[
    ["Element ID", "Element Name", "required_level"]
]

clean_essential_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
).drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# ------------------------------------------------------------
# 4. LOAD TRANSFERABLE SKILLS
# ------------------------------------------------------------

transferable = pd.read_csv(
    ONET_DIR / "transferable_skills.csv",
    low_memory=False
)

transferable_bi = transferable[
    transferable["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

importance = transferable_bi[
    transferable_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "importance"
].copy()

level = transferable_bi[
    transferable_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "level"
].copy()

importance = importance.rename(
    columns={"Data Value": "importance"}
)

level = level.rename(
    columns={"Data Value": "required_level"}
)

importance = importance[
    ["Element ID", "Element Name", "importance"]
]

level = level[
    ["Element ID", "Element Name", "required_level"]
]

clean_transferable_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
).drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# ------------------------------------------------------------
# 5. STANDARDIZE ESSENTIAL SKILLS
# ------------------------------------------------------------

essential_master = clean_essential_profile.copy()

essential_master["occupation_code"] = target_code
essential_master["occupation_title"] = occupation_title
essential_master["item_type"] = "essential_skill"
essential_master["hot_technology"] = None
essential_master["in_demand"] = None
essential_master["source"] = "O*NET"

essential_master = essential_master.rename(
    columns={
        "Element ID": "item_id",
        "Element Name": "item_name"
    }
)

# ------------------------------------------------------------
# 6. STANDARDIZE TRANSFERABLE SKILLS
# ------------------------------------------------------------

transferable_master = clean_transferable_profile.copy()

transferable_master["occupation_code"] = target_code
transferable_master["occupation_title"] = occupation_title
transferable_master["item_type"] = "transferable_skill"
transferable_master["hot_technology"] = None
transferable_master["in_demand"] = None
transferable_master["source"] = "O*NET"

transferable_master = transferable_master.rename(
    columns={
        "Element ID": "item_id",
        "Element Name": "item_name"
    }
)

# ------------------------------------------------------------
# 7. KEEP SAME COLUMN ORDER
# ------------------------------------------------------------

columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

essential_master = essential_master[columns]
transferable_master = transferable_master[columns]

# ------------------------------------------------------------
# 8. COMBINE
# ------------------------------------------------------------

master_skill_dataset = pd.concat(
    [
        essential_master,
        transferable_master
    ],
    ignore_index=True
)

# ------------------------------------------------------------
# 9. CHECK RESULT
# ------------------------------------------------------------

print("\nMASTER SKILL DATASET")
print("=" * 60)

print("Total records:", len(master_skill_dataset))

print("\nRecords by type:")
print(
    master_skill_dataset["item_type"]
    .value_counts()
)

display(master_skill_dataset)

Occupation: Business Intelligence Analysts

MASTER SKILL DATASET
============================================================
Total records: 35

Records by type:
item_type
transferable_skill    25
essential_skill       10
Name: count, dtype: int64

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.a,Reading Comprehension,4.00,4.25,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.b,Active Listening,3.88,4.00,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.c,Writing,3.75,4.00,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.d,Speaking,3.88,4.00,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.e,Mathematics,3.50,3.88,None,None,O*NET
5,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.f,Science,1.62,0.75,None,None,O*NET
6,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.a,Critical Thinking,3.88,4.25,None,None,O*NET
7,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.b,Active Learning,3.88,4.12,None,None,O*NET
8,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.c,Learning Strategies,3.00,3.00,None,None,O*NET
9,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.d,Monitoring,3.12,3.25,None,None,O*NET
10,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.a,Social Perceptiveness,2.88,2.88,None,None,O*NET
11,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.b,Coordination,3.00,3.00,None,None,O*NET
12,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.c,Persuasion,2.88,3.00,None,None,O*NET
13,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.d,Negotiation,2.50,2.88,None,None,O*NET
14,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.e,Instructing,3.00,3.00,None,None,O*NET
15,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.f,Service Orientation,2.88,2.88,None,None,O*NET
16,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.2.i,Complex Problem Solving,3.38,3.75,None,None,O*NET
17,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.a,Operations Analysis,1.88,1.62,None,None,O*NET
18,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.b,Technology Design,1.62,0.88,None,None,O*NET
19,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.c,Equipment Selection,1.00,0.00,None,None,O*NET
20,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.d,Installation,1.00,0.00,None,None,O*NET
21,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.e,Programming,2.50,2.50,None,None,O*NET
22,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.g,Operations Monitoring,1.75,1.12,None,None,O*NET
23,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.h,Operation and Control,1.38,0.38,None,None,O*NET
24,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.j,Equipment Maintenance,1.00,0.00,None,None,O*NET
25,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.k,Troubleshooting,1.00,0.00,None,None,O*NET
26,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.l,Repairing,1.00,0.00,None,None,O*NET
27,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.m,Quality Control Analysis,2.00,1.50,None,None,O*NET
28,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.4.e,Judgment and Decision Making,3.62,4.00,None,None,O*NET
29,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.4.g,Systems Analysis,3.12,3.75,None,None,O*NET
30,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.4.h,Systems Evaluation,3.12,3.75,None,None,O*NET
31,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.5.a,Time Management,3.12,3.00,None,None,O*NET
32,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.5.b,Management of Financial Resources,1.88,1.75,None,None,O*NET
33,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.5.c,Management of Material Resources,1.75,1.25,None,None,O*NET
34,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.5.d,Management of Personnel Resources,2.12,2.00,None,None,O*NET

In [15]:
# ============================================================
# STAGE 9.2 — SAVE MASTER SKILL DATASET
# ============================================================

from pathlib import Path

# Create processed-data folder
PROCESSED_DIR = Path(
    "/home/Student/career-intelligence/data/processed"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Save the master skill dataset
output_file = PROCESSED_DIR / "business_intelligence_skills.csv"

master_skill_dataset.to_csv(
    output_file,
    index=False
)

print("MASTER DATASET SAVED")
print("=" * 60)
print("File:", output_file)
print("Records:", len(master_skill_dataset))
print("Columns:", len(master_skill_dataset.columns))

print("\nColumns:")
for column in master_skill_dataset.columns:
    print("-", column)

MASTER DATASET SAVED
============================================================
File: /home/Student/career-intelligence/data/processed/business_intelligence_skills.csv
Records: 35
Columns: 10

Columns:
- occupation_code
- occupation_title
- item_type
- item_id
- item_name
- importance
- required_level
- hot_technology
- in_demand
- source

In [16]:
# ============================================================
# STAGE 10 — STANDARDIZE KNOWLEDGE DATA
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET directory
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# Load occupation data
occupation_data = pd.read_csv(
    ONET_DIR / "occupation_data.csv",
    low_memory=False
)

occupation_bi = occupation_data[
    occupation_data["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

occupation_title = occupation_bi["Title"].iloc[0]

# ------------------------------------------------------------
# LOAD KNOWLEDGE
# ------------------------------------------------------------

knowledge = pd.read_csv(
    ONET_DIR / "knowledge.csv",
    low_memory=False
)

knowledge_bi = knowledge[
    knowledge["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

# ------------------------------------------------------------
# SEPARATE IMPORTANCE AND LEVEL
# ------------------------------------------------------------

importance = knowledge_bi[
    knowledge_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "importance"
].copy()

level = knowledge_bi[
    knowledge_bi["Scale Name"].astype(str).str.strip().str.lower()
    == "level"
].copy()

# Rename values
importance = importance.rename(
    columns={"Data Value": "importance"}
)

level = level.rename(
    columns={"Data Value": "required_level"}
)

# Keep relevant columns
importance = importance[
    ["Element ID", "Element Name", "importance"]
]

level = level[
    ["Element ID", "Element Name", "required_level"]
]

# ------------------------------------------------------------
# MERGE
# ------------------------------------------------------------

clean_knowledge_profile = importance.merge(
    level,
    on=["Element ID", "Element Name"],
    how="inner"
).drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# ------------------------------------------------------------
# STANDARDIZE
# ------------------------------------------------------------

knowledge_master = clean_knowledge_profile.copy()

knowledge_master["occupation_code"] = target_code
knowledge_master["occupation_title"] = occupation_title
knowledge_master["item_type"] = "knowledge"
knowledge_master["hot_technology"] = None
knowledge_master["in_demand"] = None
knowledge_master["source"] = "O*NET"

knowledge_master = knowledge_master.rename(
    columns={
        "Element ID": "item_id",
        "Element Name": "item_name"
    }
)

# Same column order as our master dataset
columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

knowledge_master = knowledge_master[columns]

# Sort by importance
knowledge_master = knowledge_master.sort_values(
    by="importance",
    ascending=False
).reset_index(drop=True)

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("KNOWLEDGE MASTER DATASET")
print("=" * 60)
print("Records:", len(knowledge_master))

display(knowledge_master)

KNOWLEDGE MASTER DATASET
============================================================
Records: 33

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,knowledge,2.C.3.a,Computers and Electronics,4.29,5.41,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.a,Mathematics,3.82,4.67,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,knowledge,2.C.7.a,English Language,3.77,4.41,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,knowledge,2.C.1.a,Administration and Management,3.14,4.14,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,knowledge,2.C.1.e,Customer and Personal Service,3.10,3.76,None,None,O*NET
5,15-2051.01,Business Intelligence Analysts,knowledge,2.C.1.c,Economics and Accounting,3.00,3.59,None,None,O*NET
6,15-2051.01,Business Intelligence Analysts,knowledge,2.C.9.b,Communications and Media,2.59,2.95,None,None,O*NET
7,15-2051.01,Business Intelligence Analysts,knowledge,2.C.6,Education and Training,2.50,3.32,None,None,O*NET
8,15-2051.01,Business Intelligence Analysts,knowledge,2.C.1.d,Sales and Marketing,2.45,3.14,None,None,O*NET
9,15-2051.01,Business Intelligence Analysts,knowledge,2.C.3.c,Design,2.43,2.50,None,None,O*NET
10,15-2051.01,Business Intelligence Analysts,knowledge,2.C.1.b,Administrative,2.43,3.64,None,None,O*NET
11,15-2051.01,Business Intelligence Analysts,knowledge,2.C.3.b,Engineering and Technology,2.36,2.77,None,None,O*NET
12,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.f,Sociology and Anthropology,2.23,2.59,None,None,O*NET
13,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.g,Geography,2.23,3.45,None,None,O*NET
14,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.e,Psychology,2.18,2.41,None,None,O*NET
15,15-2051.01,Business Intelligence Analysts,knowledge,2.C.8.b,Law and Government,2.14,2.36,None,None,O*NET
16,15-2051.01,Business Intelligence Analysts,knowledge,2.C.1.f,Personnel and Human Resources,1.91,2.23,None,None,O*NET
17,15-2051.01,Business Intelligence Analysts,knowledge,2.C.2.a,Production and Processing,1.75,1.57,None,None,O*NET
18,15-2051.01,Business Intelligence Analysts,knowledge,2.C.7.d,History and Archeology,1.73,1.77,None,None,O*NET
19,15-2051.01,Business Intelligence Analysts,knowledge,2.C.9.a,Telecommunications,1.55,1.14,None,None,O*NET
20,15-2051.01,Business Intelligence Analysts,knowledge,2.C.8.a,Public Safety and Security,1.55,1.00,None,None,O*NET
21,15-2051.01,Business Intelligence Analysts,knowledge,2.C.7.c,Fine Arts,1.50,1.00,None,None,O*NET
22,15-2051.01,Business Intelligence Analysts,knowledge,2.C.7.e,Philosophy and Theology,1.45,1.23,None,None,O*NET
23,15-2051.01,Business Intelligence Analysts,knowledge,2.C.7.b,Foreign Language,1.36,0.77,None,None,O*NET
24,15-2051.01,Business Intelligence Analysts,knowledge,2.C.5.a,Medicine and Dentistry,1.18,0.45,None,None,O*NET
25,15-2051.01,Business Intelligence Analysts,knowledge,2.C.5.b,Therapy and Counseling,1.18,0.32,None,None,O*NET
26,15-2051.01,Business Intelligence Analysts,knowledge,2.C.10,Transportation,1.18,0.55,None,None,O*NET
27,15-2051.01,Business Intelligence Analysts,knowledge,2.C.3.d,Building and Construction,1.14,0.45,None,None,O*NET
28,15-2051.01,Business Intelligence Analysts,knowledge,2.C.2.b,Food Production,1.14,0.55,None,None,O*NET
29,15-2051.01,Business Intelligence Analysts,knowledge,2.C.3.e,Mechanical,1.14,0.32,None,None,O*NET
30,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.d,Biology,1.09,0.36,None,None,O*NET
31,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.b,Physics,1.09,0.27,None,None,O*NET
32,15-2051.01,Business Intelligence Analysts,knowledge,2.C.4.c,Chemistry,1.09,0.27,None,None,O*NET

In [17]:
# ============================================================
# STAGE 10.1 — STANDARDIZE SOFTWARE SKILLS
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET directory
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# ------------------------------------------------------------
# LOAD SOFTWARE DATA
# ------------------------------------------------------------

software = pd.read_csv(
    ONET_DIR / "software_skills.csv",
    low_memory=False
)

# Filter target occupation
software_bi = software[
    software["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

# ------------------------------------------------------------
# CLEAN SOFTWARE DATA
# ------------------------------------------------------------

software_master = software_bi[
    [
        "Element ID",
        "Element Name",
        "Hot Technology",
        "In Demand"
    ]
].copy()

# Remove duplicates
software_master = software_master.drop_duplicates(
    subset=["Element ID", "Element Name"]
)

# Remove missing names
software_master = software_master.dropna(
    subset=["Element Name"]
)

# Normalize indicator fields
for column in ["Hot Technology", "In Demand"]:
    software_master[column] = (
        software_master[column]
        .astype(str)
        .str.strip()
        .str.upper()
    )

# ------------------------------------------------------------
# ADD STANDARDIZED CAREER INFORMATION
# ------------------------------------------------------------

software_master["occupation_code"] = target_code
software_master["occupation_title"] = "Business Intelligence Analysts"
software_master["item_type"] = "software"
software_master["item_id"] = software_master["Element ID"]
software_master["item_name"] = software_master["Element Name"]

# Software does not have Importance/Required Level
software_master["importance"] = None
software_master["required_level"] = None

software_master["hot_technology"] = software_master[
    "Hot Technology"
]

software_master["in_demand"] = software_master[
    "In Demand"
]

software_master["source"] = "O*NET"

# ------------------------------------------------------------
# SELECT FINAL COLUMNS
# ------------------------------------------------------------

columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

software_master = software_master[columns]

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("SOFTWARE MASTER DATASET")
print("=" * 60)
print("Records:", len(software_master))

print("\nColumns:")
print(list(software_master.columns))

display(software_master)

SOFTWARE MASTER DATASET
============================================================
Records: 51

Columns:
['occupation_code', 'occupation_title', 'item_type', 'item_id', 'item_name', 'importance', 'required_level', 'hot_technology', 'in_demand', 'source']

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
11952,15-2051.01,Business Intelligence Analysts,software,2.E.6.e,Data base reporting software,None,None,N,N,O*NET
11953,15-2051.01,Business Intelligence Analysts,software,2.E.5.b,Document management software,None,None,Y,N,O*NET
11954,15-2051.01,Business Intelligence Analysts,software,2.E.7.b,Development environment software,None,None,N,N,O*NET
11955,15-2051.01,Business Intelligence Analysts,software,2.E.4.g,Web page creation and editing software,None,None,N,N,O*NET
11956,15-2051.01,Business Intelligence Analysts,software,2.E.7.e,Object or component oriented development software,None,None,N,N,O*NET
11957,15-2051.01,Business Intelligence Analysts,software,2.E.6.f,Data base user interface and query software,None,None,N,N,O*NET
11958,15-2051.01,Business Intelligence Analysts,software,2.E.7.h,Web platform development software,None,None,Y,N,O*NET
11959,15-2051.01,Business Intelligence Analysts,software,2.E.6.m,Business intelligence and data analysis software,None,None,Y,N,O*NET
11960,15-2051.01,Business Intelligence Analysts,software,2.E.6.d,Data base management system software,None,None,Y,N,O*NET
11969,15-2051.01,Business Intelligence Analysts,software,2.E.6.k,Portal server software,None,None,N,N,O*NET
11976,15-2051.01,Business Intelligence Analysts,software,2.E.1.e,Project management software,None,None,Y,N,O*NET
11977,15-2051.01,Business Intelligence Analysts,software,2.E.5.a,Content workflow software,None,None,Y,N,O*NET
11978,15-2051.01,Business Intelligence Analysts,software,2.E.13.c,Operating system software,None,None,Y,N,O*NET
11979,15-2051.01,Business Intelligence Analysts,software,2.E.6.c,Customer relationship management CRM software,None,None,N,N,O*NET
11984,15-2051.01,Business Intelligence Analysts,software,2.E.12.a,Access software,None,None,N,N,O*NET
11986,15-2051.01,Business Intelligence Analysts,software,2.E.6.l,Transaction server software,None,None,N,N,O*NET
11987,15-2051.01,Business Intelligence Analysts,software,2.E.6.i,Metadata management software,None,None,N,N,O*NET
11988,15-2051.01,Business Intelligence Analysts,software,2.E.6.g,Data mining software,None,None,N,N,O*NET
11990,15-2051.01,Business Intelligence Analysts,software,2.E.2.d,Financial analysis software,None,None,N,N,O*NET
11995,15-2051.01,Business Intelligence Analysts,software,2.E.10.b,Desktop communications software,None,None,N,N,O*NET
11998,15-2051.01,Business Intelligence Analysts,software,2.E.9.i,Medical software,None,None,Y,N,O*NET
11999,15-2051.01,Business Intelligence Analysts,software,2.E.8.h,Geographic information system,None,None,Y,N,O*NET
12002,15-2051.01,Business Intelligence Analysts,software,2.E.7.c,Enterprise application integration software,None,None,Y,N,O*NET
12005,15-2051.01,Business Intelligence Analysts,software,2.E.2.a,Accounting software,None,None,N,N,O*NET
12007,15-2051.01,Business Intelligence Analysts,software,2.E.5.c,File versioning software,None,None,Y,N,O*NET
12008,15-2051.01,Business Intelligence Analysts,software,2.E.10.a,Application server software,None,None,Y,N,O*NET
12010,15-2051.01,Business Intelligence Analysts,software,2.E.1.l,Sales and marketing software,None,None,N,N,O*NET
12012,15-2051.01,Business Intelligence Analysts,software,2.E.4.d,Word processing software,None,None,Y,N,O*NET
12015,15-2051.01,Business Intelligence Analysts,software,2.E.4.f,Presentation software,None,None,N,N,O*NET
12018,15-2051.01,Business Intelligence Analysts,software,2.E.7.f,Program testing software,None,None,N,N,O*NET
12019,15-2051.01,Business Intelligence Analysts,software,2.E.6.j,Object oriented data base management software,None,None,Y,N,O*NET
12020,15-2051.01,Business Intelligence Analysts,software,2.E.1.c,Human resources software,None,None,N,N,O*NET
12024,15-2051.01,Business Intelligence Analysts,software,2.E.12.b,Communications server software,None,None,N,N,O*NET
12026,15-2051.01,Business Intelligence Analysts,software,2.E.16.a,Electronic mail software,None,None,N,N,O*NET
12027,15-2051.01,Business Intelligence Analysts,software,2.E.17.a,Enterprise system management software,None,None,N,N,O*NET
12028,15-2051.01,Business Intelligence Analysts,software,2.E.9.d,Analytical or scientific software,None,None,Y,N,O*NET
12030,15-2051.01,Business Intelligence Analysts,software,2.E.11.e,Cloud-based management software,None,None,N,N,O*NET
12041,15-2051.01,Business Intelligence Analysts,software,2.E.6.h,Information retrieval or search software,None,None,N,N,O*NET
12044,15-2051.01,Business Intelligence Analysts,software,2.E.14.d,Transaction security and virus protection soft...,None,None,N,N,O*NET
12054,15-2051.01,Business Intelligence Analysts,software,2.E.2.b,Enterprise resource planning ERP software,None,None,N,N,O*NET
12056,15-2051.01,Business Intelligence Analysts,software,2.E.4.i,Spreadsheet software,None,None,Y,Y,O*NET
12058,15-2051.01,Business Intelligence Analysts,software,2.E.1.k,Office suite software,None,None,Y,Y,O*NET
12067,15-2051.01,Business Intelligence Analysts,software,2.E.4.k,Desktop publishing software,None,None,N,N,O*NET
12072,15-2051.01,Business Intelligence Analysts,software,2.E.1.p,Process mapping and design software,None,None,Y,N,O*NET
12083,15-2051.01,Business Intelligence Analysts,software,2.E.11.a,Network monitoring software,None,None,N,N,O*NET
12112,15-2051.01,Business Intelligence Analysts,software,2.E.9.c,Computer aided design CAD software,None,None,N,N,O*NET
12125,15-2051.01,Business Intelligence Analysts,software,2.E.7.d,Graphical user interface development software,None,None,N,N,O*NET
12148,15-2051.01,Business Intelligence Analysts,software,2.E.7.g,Requirements analysis and system architecture ...,None,None,N,N,O*NET
12151,15-2051.01,Business Intelligence Analysts,software,2.E.15.f,Backup or archival software,None,None,N,N,O*NET
12152,15-2051.01,Business Intelligence Analysts,software,2.E.14.c,Network security and virtual private network V...,None,None,N,N,O*NET
12154,15-2051.01,Business Intelligence Analysts,software,2.E.4.c,Video creation and editing software,None,None,N,N,O*NET

In [19]:
# ============================================================
# STAGE 10.2 — BUILD COMPLETE CAREER INTELLIGENCE PROFILE
# WARNING-FREE VERSION
# ============================================================

import pandas as pd

columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

# Make copies
essential_final = essential_master[columns].copy()
transferable_final = transferable_master[columns].copy()
knowledge_final = knowledge_master[columns].copy()
software_final = software_master[columns].copy()

# Explicitly set empty numeric fields to numeric NA
for df in [
    essential_final,
    transferable_final,
    knowledge_final,
    software_final
]:
    df["importance"] = pd.to_numeric(
        df["importance"],
        errors="coerce"
    )
    
    df["required_level"] = pd.to_numeric(
        df["required_level"],
        errors="coerce"
    )

# Combine the datasets
career_profile = pd.concat(
    [
        essential_final,
        transferable_final,
        knowledge_final,
        software_final
    ],
    ignore_index=True
)

# Remove exact duplicate rows
career_profile = (
    career_profile
    .drop_duplicates()
    .reset_index(drop=True)
)

# ============================================================
# CHECK DATASET
# ============================================================

print("CAREER INTELLIGENCE PROFILE")
print("=" * 60)

print("Occupation:", career_profile["occupation_title"].iloc[0])
print("Occupation code:", career_profile["occupation_code"].iloc[0])

print("\nTotal records:", len(career_profile))

print("\nRecords by type:")
print(
    career_profile["item_type"]
    .value_counts()
)

print("\nMissing values:")
print(
    career_profile.isna().sum()
)

print("\nDataset preview:")
display(career_profile.head(20))

CAREER INTELLIGENCE PROFILE
============================================================
Occupation: Business Intelligence Analysts
Occupation code: 15-2051.01

Total records: 119

Records by type:
item_type
software              51
knowledge             33
transferable_skill    25
essential_skill       10
Name: count, dtype: int64

Missing values:
occupation_code      0
occupation_title     0
item_type            0
item_id              0
item_name            0
importance          51
required_level      51
hot_technology      68
in_demand           68
source               0
dtype: int64

Dataset preview:

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.a,Reading Comprehension,4.00,4.25,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.b,Active Listening,3.88,4.00,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.c,Writing,3.75,4.00,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.d,Speaking,3.88,4.00,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.e,Mathematics,3.50,3.88,None,None,O*NET
5,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.1.f,Science,1.62,0.75,None,None,O*NET
6,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.a,Critical Thinking,3.88,4.25,None,None,O*NET
7,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.b,Active Learning,3.88,4.12,None,None,O*NET
8,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.c,Learning Strategies,3.00,3.00,None,None,O*NET
9,15-2051.01,Business Intelligence Analysts,essential_skill,2.A.2.d,Monitoring,3.12,3.25,None,None,O*NET
10,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.a,Social Perceptiveness,2.88,2.88,None,None,O*NET
11,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.b,Coordination,3.00,3.00,None,None,O*NET
12,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.c,Persuasion,2.88,3.00,None,None,O*NET
13,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.d,Negotiation,2.50,2.88,None,None,O*NET
14,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.e,Instructing,3.00,3.00,None,None,O*NET
15,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.1.f,Service Orientation,2.88,2.88,None,None,O*NET
16,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.2.i,Complex Problem Solving,3.38,3.75,None,None,O*NET
17,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.a,Operations Analysis,1.88,1.62,None,None,O*NET
18,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.b,Technology Design,1.62,0.88,None,None,O*NET
19,15-2051.01,Business Intelligence Analysts,transferable_skill,2.B.3.c,Equipment Selection,1.00,0.00,None,None,O*NET

In [20]:
# ============================================================
# STAGE 10.3 — SAVE CAREER PROFILE
# ============================================================

from pathlib import Path

PROCESSED_DIR = Path(
    "/home/Student/career-intelligence/data/processed"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Save complete career profile
career_profile_file = (
    PROCESSED_DIR /
    "business_intelligence_career_profile.csv"
)

career_profile.to_csv(
    career_profile_file,
    index=False
)

print("CAREER PROFILE SAVED")
print("=" * 60)
print("File:", career_profile_file)
print("Records:", len(career_profile))
print("File exists:", career_profile_file.exists())

CAREER PROFILE SAVED
============================================================
File: /home/Student/career-intelligence/data/processed/business_intelligence_career_profile.csv
Records: 119
File exists: True

In [21]:
# ============================================================
# STAGE 11 — CLEAN TASK STATEMENTS
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET directory
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

# Target occupation
target_code = "15-2051.01"

# ------------------------------------------------------------
# LOAD TASK STATEMENTS
# ------------------------------------------------------------

tasks = pd.read_csv(
    ONET_DIR / "task_statements.csv",
    low_memory=False
)

# Filter Business Intelligence Analysts
tasks_bi = tasks[
    tasks["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("Raw task records:", len(tasks_bi))

# ------------------------------------------------------------
# REMOVE EMPTY COLUMNS AND DUPLICATES
# ------------------------------------------------------------

clean_tasks = tasks_bi.dropna(
    axis=1,
    how="all"
).drop_duplicates().reset_index(drop=True)

print("Clean task records:", len(clean_tasks))

# ------------------------------------------------------------
# IDENTIFY TASK DESCRIPTION COLUMN
# ------------------------------------------------------------

print("\nColumns available:")
print(list(clean_tasks.columns))

task_columns = [
    column for column in clean_tasks.columns
    if "task" in column.lower()
    and "id" not in column.lower()
]

print("\nPossible task description columns:")
print(task_columns)

# ------------------------------------------------------------
# DISPLAY TASKS
# ------------------------------------------------------------

display(clean_tasks)

Raw task records: 17
Clean task records: 17

Columns available:
['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type', 'Incumbents Responding', 'Date', 'Domain Source']

Possible task description columns:
['Task', 'Task Type']

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,15-2051.01,Business Intelligence Analysts,16150,Generate standard or custom reports summarizin...,Core,22.0,08/2024,Occupational Expert
1,15-2051.01,Business Intelligence Analysts,16139,Maintain or update business intelligence tools...,Core,22.0,08/2024,Occupational Expert
2,15-2051.01,Business Intelligence Analysts,16140,Manage timely flow of business intelligence in...,Core,22.0,08/2024,Occupational Expert
3,15-2051.01,Business Intelligence Analysts,16134,Provide technical support for existing reports...,Core,21.0,08/2024,Occupational Expert
4,15-2051.01,Business Intelligence Analysts,16141,Identify and analyze industry or geographic tr...,Core,22.0,08/2024,Occupational Expert
5,15-2051.01,Business Intelligence Analysts,16142,Document specifications for business intellige...,Core,22.0,08/2024,Occupational Expert
6,15-2051.01,Business Intelligence Analysts,16144,"Create business intelligence tools or systems,...",Core,21.0,08/2024,Occupational Expert
7,15-2051.01,Business Intelligence Analysts,16146,Collect business intelligence data from availa...,Core,22.0,08/2024,Occupational Expert
8,15-2051.01,Business Intelligence Analysts,16143,"Disseminate information regarding tools, repor...",Core,21.0,08/2024,Occupational Expert
9,15-2051.01,Business Intelligence Analysts,16145,Conduct or coordinate tests to ensure that int...,Core,22.0,08/2024,Occupational Expert
10,15-2051.01,Business Intelligence Analysts,16149,Synthesize current business intelligence or tr...,Core,22.0,08/2024,Occupational Expert
11,15-2051.01,Business Intelligence Analysts,16148,Analyze competitive market strategies through ...,Core,22.0,08/2024,Occupational Expert
12,15-2051.01,Business Intelligence Analysts,16136,Identify or monitor current and potential cust...,Core,22.0,08/2024,Occupational Expert
13,15-2051.01,Business Intelligence Analysts,16138,"Communicate with customers, competitors, suppl...",Core,22.0,08/2024,Occupational Expert
14,15-2051.01,Business Intelligence Analysts,16135,"Maintain library of model documents, templates...",Core,22.0,08/2024,Occupational Expert
15,15-2051.01,Business Intelligence Analysts,16137,Create or review technical design documentatio...,Core,22.0,08/2024,Occupational Expert
16,15-2051.01,Business Intelligence Analysts,16147,Analyze technology trends to identify markets ...,Core,22.0,08/2024,Occupational Expert

In [22]:
# ============================================================
# STAGE 11.1 — STANDARDIZE TASK DATA
# ============================================================

import pandas as pd

# Make a copy
tasks_master = clean_tasks.copy()

# ------------------------------------------------------------
# FIND THE TASK DESCRIPTION COLUMN
# ------------------------------------------------------------

task_columns = [
    col for col in tasks_master.columns
    if "task" in col.lower()
    and "id" not in col.lower()
]

print("Possible task columns:")
print(task_columns)

# Use the first task-description column found
task_column = task_columns[0]

# ------------------------------------------------------------
# CREATE STANDARDIZED TASK DATASET
# ------------------------------------------------------------

tasks_master["occupation_code"] = target_code
tasks_master["occupation_title"] = "Business Intelligence Analysts"

tasks_master["item_type"] = "task"

tasks_master["item_id"] = range(
    1,
    len(tasks_master) + 1
)

tasks_master["item_name"] = (
    tasks_master[task_column]
    .astype(str)
    .str.strip()
)

tasks_master["importance"] = None
tasks_master["required_level"] = None
tasks_master["hot_technology"] = None
tasks_master["in_demand"] = None
tasks_master["source"] = "O*NET"

# ------------------------------------------------------------
# SELECT STANDARDIZED COLUMNS
# ------------------------------------------------------------

task_columns_final = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

tasks_master = tasks_master[
    task_columns_final
].copy()

# Remove empty task names
tasks_master = tasks_master[
    tasks_master["item_name"].notna()
]

tasks_master = tasks_master[
    tasks_master["item_name"] != "nan"
]

# Reset index
tasks_master = tasks_master.reset_index(drop=True)

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("\nSTANDARDIZED TASK DATASET")
print("=" * 60)
print("Records:", len(tasks_master))

display(tasks_master)

Possible task columns:
['Task', 'Task Type']

STANDARDIZED TASK DATASET
============================================================
Records: 17

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,task,1,Generate standard or custom reports summarizin...,None,None,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,task,2,Maintain or update business intelligence tools...,None,None,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,task,3,Manage timely flow of business intelligence in...,None,None,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,task,4,Provide technical support for existing reports...,None,None,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,task,5,Identify and analyze industry or geographic tr...,None,None,None,None,O*NET
5,15-2051.01,Business Intelligence Analysts,task,6,Document specifications for business intellige...,None,None,None,None,O*NET
6,15-2051.01,Business Intelligence Analysts,task,7,"Create business intelligence tools or systems,...",None,None,None,None,O*NET
7,15-2051.01,Business Intelligence Analysts,task,8,Collect business intelligence data from availa...,None,None,None,None,O*NET
8,15-2051.01,Business Intelligence Analysts,task,9,"Disseminate information regarding tools, repor...",None,None,None,None,O*NET
9,15-2051.01,Business Intelligence Analysts,task,10,Conduct or coordinate tests to ensure that int...,None,None,None,None,O*NET
10,15-2051.01,Business Intelligence Analysts,task,11,Synthesize current business intelligence or tr...,None,None,None,None,O*NET
11,15-2051.01,Business Intelligence Analysts,task,12,Analyze competitive market strategies through ...,None,None,None,None,O*NET
12,15-2051.01,Business Intelligence Analysts,task,13,Identify or monitor current and potential cust...,None,None,None,None,O*NET
13,15-2051.01,Business Intelligence Analysts,task,14,"Communicate with customers, competitors, suppl...",None,None,None,None,O*NET
14,15-2051.01,Business Intelligence Analysts,task,15,"Maintain library of model documents, templates...",None,None,None,None,O*NET
15,15-2051.01,Business Intelligence Analysts,task,16,Create or review technical design documentatio...,None,None,None,None,O*NET
16,15-2051.01,Business Intelligence Analysts,task,17,Analyze technology trends to identify markets ...,None,None,None,None,O*NET

In [23]:
# ============================================================
# STAGE 11.2 — SAVE STANDARDIZED TASK DATA
# ============================================================

from pathlib import Path

PROCESSED_DIR = Path(
    "/home/Student/career-intelligence/data/processed"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

task_file = PROCESSED_DIR / "business_intelligence_tasks.csv"

tasks_master.to_csv(
    task_file,
    index=False
)

print("TASK DATASET SAVED")
print("=" * 60)
print("File:", task_file)
print("Records:", len(tasks_master))
print("File exists:", task_file.exists())

TASK DATASET SAVED
============================================================
File: /home/Student/career-intelligence/data/processed/business_intelligence_tasks.csv
Records: 17
File exists: True

In [24]:
# ============================================================
# STAGE 12 — CLEAN WORK ACTIVITIES
# ============================================================

from pathlib import Path
import pandas as pd

# O*NET directory
ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

# Target occupation
target_code = "15-2051.01"

# ------------------------------------------------------------
# LOAD WORK ACTIVITIES
# ------------------------------------------------------------

work_activities = pd.read_csv(
    ONET_DIR / "work_activities.csv",
    low_memory=False
)

# Filter Business Intelligence Analysts
work_bi = work_activities[
    work_activities["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("Raw work-activity records:", len(work_bi))

# ------------------------------------------------------------
# REMOVE EMPTY COLUMNS AND DUPLICATES
# ------------------------------------------------------------

clean_work_activities = (
    work_bi
    .dropna(axis=1, how="all")
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Clean work-activity records:", len(clean_work_activities))

# ------------------------------------------------------------
# SHOW AVAILABLE COLUMNS
# ------------------------------------------------------------

print("\nAvailable columns:")
print(list(clean_work_activities.columns))

# ------------------------------------------------------------
# DISPLAY RECORDS
# ------------------------------------------------------------

display(clean_work_activities)

Raw work-activity records: 82
Clean work-activity records: 82

Available columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Not Relevant', 'Date', 'Domain Source']

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Not Relevant,Date,Domain Source
0,15-2051.01,Business Intelligence Analysts,4.A.1.a.1,Getting Information,IM,Importance,4.50,22.0,NaN,08/2024,Occupational Expert
1,15-2051.01,Business Intelligence Analysts,4.A.1.a.1,Getting Information,LV,Level,5.41,22.0,N,08/2024,Occupational Expert
2,15-2051.01,Business Intelligence Analysts,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,2.76,21.0,NaN,08/2024,Occupational Expert
3,15-2051.01,Business Intelligence Analysts,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",LV,Level,3.29,21.0,N,08/2024,Occupational Expert
4,15-2051.01,Business Intelligence Analysts,4.A.1.b.1,"Identifying Objects, Actions, and Events",IM,Importance,3.91,22.0,NaN,08/2024,Occupational Expert
...,...,...,...,...,...,...,...,...,...,...,...
77,15-2051.01,Business Intelligence Analysts,4.A.4.c.1,Performing Administrative Activities,LV,Level,2.82,22.0,N,08/2024,Occupational Expert
78,15-2051.01,Business Intelligence Analysts,4.A.4.c.2,Staffing Organizational Units,IM,Importance,1.90,21.0,NaN,08/2024,Occupational Expert
79,15-2051.01,Business Intelligence Analysts,4.A.4.c.2,Staffing Organizational Units,LV,Level,2.23,22.0,N,08/2024,Occupational Expert
80,15-2051.01,Business Intelligence Analysts,4.A.4.c.3,Monitoring and Controlling Resources,IM,Importance,2.09,22.0,NaN,08/2024,Occupational Expert
81,15-2051.01,Business Intelligence Analysts,4.A.4.c.3,Monitoring and Controlling Resources,LV,Level,2.14,22.0,N,08/2024,Occupational Expert

In [25]:
# ============================================================
# STAGE 12.1 — STANDARDIZE WORK ACTIVITIES
# ============================================================

import pandas as pd

# Make a copy
activities_master = clean_work_activities.copy()

# ------------------------------------------------------------
# FIND ACTIVITY DESCRIPTION COLUMN
# ------------------------------------------------------------

print("Available columns:")
print(list(activities_master.columns))

activity_columns = [
    col for col in activities_master.columns
    if (
        "element name" in col.lower()
        or "activity" in col.lower()
    )
]

print("\nPossible activity-name columns:")
print(activity_columns)

# ------------------------------------------------------------
# SELECT ACTIVITY NAME
# ------------------------------------------------------------

activity_column = activity_columns[0]

# ------------------------------------------------------------
# CREATE STANDARDIZED DATASET
# ------------------------------------------------------------

activities_master["occupation_code"] = target_code
activities_master["occupation_title"] = "Business Intelligence Analysts"
activities_master["item_type"] = "work_activity"

# Give each activity a simple internal ID
activities_master["item_id"] = [
    f"WA_{i:03d}"
    for i in range(1, len(activities_master) + 1)
]

activities_master["item_name"] = (
    activities_master[activity_column]
    .astype(str)
    .str.strip()
)

# These fields are not provided by the work-activities table
activities_master["importance"] = None
activities_master["required_level"] = None
activities_master["hot_technology"] = None
activities_master["in_demand"] = None
activities_master["source"] = "O*NET"

# ------------------------------------------------------------
# SELECT FINAL COLUMNS
# ------------------------------------------------------------

activity_final_columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

activities_master = activities_master[
    activity_final_columns
].copy()

# Remove empty activity names
activities_master = activities_master[
    activities_master["item_name"].notna()
]

activities_master = activities_master[
    activities_master["item_name"] != "nan"
]

activities_master = (
    activities_master
    .drop_duplicates()
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("\nSTANDARDIZED WORK ACTIVITIES")
print("=" * 60)
print("Records:", len(activities_master))

display(activities_master)

Available columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Not Relevant', 'Date', 'Domain Source']

Possible activity-name columns:
['Element Name']

STANDARDIZED WORK ACTIVITIES
============================================================
Records: 82

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,work_activity,WA_001,Getting Information,None,None,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,work_activity,WA_002,Getting Information,None,None,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,work_activity,WA_003,"Monitoring Processes, Materials, or Surroundings",None,None,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,work_activity,WA_004,"Monitoring Processes, Materials, or Surroundings",None,None,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,work_activity,WA_005,"Identifying Objects, Actions, and Events",None,None,None,None,O*NET
...,...,...,...,...,...,...,...,...,...,...
77,15-2051.01,Business Intelligence Analysts,work_activity,WA_078,Performing Administrative Activities,None,None,None,None,O*NET
78,15-2051.01,Business Intelligence Analysts,work_activity,WA_079,Staffing Organizational Units,None,None,None,None,O*NET
79,15-2051.01,Business Intelligence Analysts,work_activity,WA_080,Staffing Organizational Units,None,None,None,None,O*NET
80,15-2051.01,Business Intelligence Analysts,work_activity,WA_081,Monitoring and Controlling Resources,None,None,None,None,O*NET
81,15-2051.01,Business Intelligence Analysts,work_activity,WA_082,Monitoring and Controlling Resources,None,None,None,None,O*NET

In [26]:
# ============================================================
# STAGE 12.2 — SAVE STANDARDIZED WORK ACTIVITIES
# ============================================================

from pathlib import Path

PROCESSED_DIR = Path(
    "/home/Student/career-intelligence/data/processed"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

activity_file = (
    PROCESSED_DIR /
    "business_intelligence_work_activities.csv"
)

activities_master.to_csv(
    activity_file,
    index=False
)

print("WORK ACTIVITIES DATASET SAVED")
print("=" * 60)
print("File:", activity_file)
print("Records:", len(activities_master))
print("File exists:", activity_file.exists())

WORK ACTIVITIES DATASET SAVED
============================================================
File: /home/Student/career-intelligence/data/processed/business_intelligence_work_activities.csv
Records: 82
File exists: True

In [27]:
# ============================================================
# STAGE 13 — STANDARDIZE EDUCATION DATA
# ============================================================

from pathlib import Path
import pandas as pd

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# Load education data
education = pd.read_csv(
    ONET_DIR / "education.csv",
    low_memory=False
)

# Filter target occupation
education_bi = education[
    education["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

print("Raw education records:", len(education_bi))

# Remove completely empty columns and duplicates
education_master = (
    education_bi
    .dropna(axis=1, how="all")
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Clean education records:", len(education_master))

print("\nAvailable columns:")
print(list(education_master.columns))

display(education_master)

Raw education records: 13
Clean education records: 13

Available columns:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Date', 'Domain Source']

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Date,Domain Source
0,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),1.0,0.00,22,08/2024,Occupational Expert
1,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),2.0,0.00,22,08/2024,Occupational Expert
2,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),3.0,0.00,22,08/2024,Occupational Expert
3,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),4.0,0.00,22,08/2024,Occupational Expert
4,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),5.0,4.55,22,08/2024,Occupational Expert
5,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),6.0,68.18,22,08/2024,Occupational Expert
6,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),7.0,4.55,22,08/2024,Occupational Expert
7,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),8.0,22.73,22,08/2024,Occupational Expert
8,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),9.0,0.00,22,08/2024,Occupational Expert
9,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),10.0,0.00,22,08/2024,Occupational Expert
10,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),11.0,0.00,22,08/2024,Occupational Expert
11,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),12.0,0.00,22,08/2024,Occupational Expert
12,15-2051.01,Business Intelligence Analysts,2.D.4.a,Job-Related Professional Certification,IM,Importance,NaN,1.82,22,08/2024,Occupational Expert

In [28]:
# ============================================================
# STAGE 13.1 — INSPECT EDUCATION DATA
# ============================================================

print("EDUCATION COLUMNS")
print("=" * 60)

for i, column in enumerate(education_master.columns, start=1):
    print(f"{i}. {column}")

print("\nEDUCATION DATA PREVIEW")
print("=" * 60)

display(education_master)

EDUCATION COLUMNS
============================================================
1. O*NET-SOC Code
2. Title
3. Element ID
4. Element Name
5. Scale ID
6. Scale Name
7. Category
8. Data Value
9. N
10. Date
11. Domain Source

EDUCATION DATA PREVIEW
============================================================

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Date,Domain Source
0,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),1.0,0.00,22,08/2024,Occupational Expert
1,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),2.0,0.00,22,08/2024,Occupational Expert
2,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),3.0,0.00,22,08/2024,Occupational Expert
3,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),4.0,0.00,22,08/2024,Occupational Expert
4,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),5.0,4.55,22,08/2024,Occupational Expert
5,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),6.0,68.18,22,08/2024,Occupational Expert
6,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),7.0,4.55,22,08/2024,Occupational Expert
7,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),8.0,22.73,22,08/2024,Occupational Expert
8,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),9.0,0.00,22,08/2024,Occupational Expert
9,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),10.0,0.00,22,08/2024,Occupational Expert
10,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),11.0,0.00,22,08/2024,Occupational Expert
11,15-2051.01,Business Intelligence Analysts,2.D.1,Required Level of Education,RL,Required Level Of Education (Categories 1-12),12.0,0.00,22,08/2024,Occupational Expert
12,15-2051.01,Business Intelligence Analysts,2.D.4.a,Job-Related Professional Certification,IM,Importance,NaN,1.82,22,08/2024,Occupational Expert

In [29]:
# ============================================================
# STAGE 13.2 — STANDARDIZE EDUCATION DATA
# ============================================================

import pandas as pd

# Make a copy
education_std = education_master.copy()

# ------------------------------------------------------------
# CLEAN TEXT FIELDS
# ------------------------------------------------------------

text_columns = [
    "O*NET-SOC Code",
    "Title",
    "Element ID",
    "Element Name",
    "Scale ID",
    "Scale Name",
    "Category",
    "Domain Source"
]

for column in text_columns:
    if column in education_std.columns:
        education_std[column] = (
            education_std[column]
            .astype(str)
            .str.strip()
        )

# ------------------------------------------------------------
# CONVERT DATA VALUE TO NUMERIC
# ------------------------------------------------------------

education_std["Data Value"] = pd.to_numeric(
    education_std["Data Value"],
    errors="coerce"
)

# ------------------------------------------------------------
# CREATE STANDARDIZED FIELDS
# ------------------------------------------------------------

education_std["occupation_code"] = target_code
education_std["occupation_title"] = education_std["Title"]

education_std["item_type"] = "education"

education_std["item_id"] = education_std["Element ID"]

education_std["item_name"] = education_std["Category"]

education_std["importance"] = None
education_std["required_level"] = education_std["Data Value"]

education_std["hot_technology"] = None
education_std["in_demand"] = None

education_std["source"] = "O*NET"

# ------------------------------------------------------------
# SELECT FINAL COLUMNS
# ------------------------------------------------------------

education_final_columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

education_standardized = education_std[
    education_final_columns
].copy()

# Remove duplicates
education_standardized = (
    education_standardized
    .drop_duplicates()
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("STANDARDIZED EDUCATION DATASET")
print("=" * 60)
print("Records:", len(education_standardized))

display(education_standardized)

STANDARDIZED EDUCATION DATASET
============================================================
Records: 13

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,education,2.D.1,1.0,None,0.00,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,education,2.D.1,2.0,None,0.00,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,education,2.D.1,3.0,None,0.00,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,education,2.D.1,4.0,None,0.00,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,education,2.D.1,5.0,None,4.55,None,None,O*NET
5,15-2051.01,Business Intelligence Analysts,education,2.D.1,6.0,None,68.18,None,None,O*NET
6,15-2051.01,Business Intelligence Analysts,education,2.D.1,7.0,None,4.55,None,None,O*NET
7,15-2051.01,Business Intelligence Analysts,education,2.D.1,8.0,None,22.73,None,None,O*NET
8,15-2051.01,Business Intelligence Analysts,education,2.D.1,9.0,None,0.00,None,None,O*NET
9,15-2051.01,Business Intelligence Analysts,education,2.D.1,10.0,None,0.00,None,None,O*NET
10,15-2051.01,Business Intelligence Analysts,education,2.D.1,11.0,None,0.00,None,None,O*NET
11,15-2051.01,Business Intelligence Analysts,education,2.D.1,12.0,None,0.00,None,None,O*NET
12,15-2051.01,Business Intelligence Analysts,education,2.D.4.a,nan,None,1.82,None,None,O*NET

In [30]:
# ============================================================
# STAGE 14 — INSPECT TRAINING & EXPERIENCE
# ============================================================

from pathlib import Path
import pandas as pd

ONET_DIR = Path(
    "/home/Student/career-intelligence/data/raw/onet/db_31_0_csv"
)

target_code = "15-2051.01"

# Load training and experience data
training = pd.read_csv(
    ONET_DIR / "training_and_experience.csv",
    low_memory=False
)

# Filter target occupation
training_bi = training[
    training["O*NET-SOC Code"].astype(str).str.strip()
    == target_code
].copy()

# Clean empty columns and duplicates
training_master = (
    training_bi
    .dropna(axis=1, how="all")
    .drop_duplicates()
    .reset_index(drop=True)
)

print("TRAINING & EXPERIENCE")
print("=" * 60)
print("Raw records:", len(training_bi))
print("Clean records:", len(training_master))

print("\nColumns:")
for i, column in enumerate(training_master.columns, start=1):
    print(f"{i}. {column}")

print("\nData preview:")
display(training_master)

TRAINING & EXPERIENCE
============================================================
Raw records: 30
Clean records: 30

Columns:
1. O*NET-SOC Code
2. Title
3. Element ID
4. Element Name
5. Scale ID
6. Scale Name
7. Category
8. Data Value
9. N
10. Date
11. Domain Source

Data preview:

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Date,Domain Source
0,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),1.0,0.00,22,08/2024,Occupational Expert
1,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),2.0,0.00,22,08/2024,Occupational Expert
2,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),3.0,0.00,22,08/2024,Occupational Expert
3,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),4.0,0.00,22,08/2024,Occupational Expert
4,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),5.0,9.09,22,08/2024,Occupational Expert
5,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),6.0,13.64,22,08/2024,Occupational Expert
6,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),7.0,36.36,22,08/2024,Occupational Expert
7,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),8.0,31.82,22,08/2024,Occupational Expert
8,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),9.0,9.09,22,08/2024,Occupational Expert
9,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),10.0,0.00,22,08/2024,Occupational Expert
10,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),11.0,0.00,22,08/2024,Occupational Expert
11,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),1.0,27.27,22,08/2024,Occupational Expert
12,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),2.0,13.64,22,08/2024,Occupational Expert
13,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),3.0,13.64,22,08/2024,Occupational Expert
14,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),4.0,13.64,22,08/2024,Occupational Expert
15,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),5.0,13.64,22,08/2024,Occupational Expert
16,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),6.0,13.64,22,08/2024,Occupational Expert
17,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),7.0,0.00,22,08/2024,Occupational Expert
18,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),8.0,4.55,22,08/2024,Occupational Expert
19,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),9.0,0.00,22,08/2024,Occupational Expert
20,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),1.0,13.64,22,08/2024,Occupational Expert
21,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),2.0,9.09,22,08/2024,Occupational Expert
22,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),3.0,18.18,22,08/2024,Occupational Expert
23,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),4.0,18.18,22,08/2024,Occupational Expert
24,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),5.0,31.82,22,08/2024,Occupational Expert
25,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),6.0,4.55,22,08/2024,Occupational Expert
26,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),7.0,4.55,22,08/2024,Occupational Expert
27,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),8.0,0.00,22,08/2024,Occupational Expert
28,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),9.0,0.00,22,08/2024,Occupational Expert
29,15-2051.01,Business Intelligence Analysts,3.A.4.a,Job-related Apprenticeship,IM,Importance,NaN,1.82,22,08/2024,Occupational Expert

In [31]:
# ============================================================
# STAGE 14.1 — INSPECT TRAINING & EXPERIENCE COLUMNS
# ============================================================

print("TRAINING & EXPERIENCE COLUMNS")
print("=" * 60)

for i, column in enumerate(training_master.columns, start=1):
    print(f"{i}. {column}")

print("\nTRAINING & EXPERIENCE DATA PREVIEW")
print("=" * 60)

display(training_master)

TRAINING & EXPERIENCE COLUMNS
============================================================
1. O*NET-SOC Code
2. Title
3. Element ID
4. Element Name
5. Scale ID
6. Scale Name
7. Category
8. Data Value
9. N
10. Date
11. Domain Source

TRAINING & EXPERIENCE DATA PREVIEW
============================================================

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Date,Domain Source
0,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),1.0,0.00,22,08/2024,Occupational Expert
1,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),2.0,0.00,22,08/2024,Occupational Expert
2,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),3.0,0.00,22,08/2024,Occupational Expert
3,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),4.0,0.00,22,08/2024,Occupational Expert
4,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),5.0,9.09,22,08/2024,Occupational Expert
5,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),6.0,13.64,22,08/2024,Occupational Expert
6,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),7.0,36.36,22,08/2024,Occupational Expert
7,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),8.0,31.82,22,08/2024,Occupational Expert
8,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),9.0,9.09,22,08/2024,Occupational Expert
9,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),10.0,0.00,22,08/2024,Occupational Expert
10,15-2051.01,Business Intelligence Analysts,3.A.1,Related Work Experience,RW,Related Work Experience (Categories 1-11),11.0,0.00,22,08/2024,Occupational Expert
11,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),1.0,27.27,22,08/2024,Occupational Expert
12,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),2.0,13.64,22,08/2024,Occupational Expert
13,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),3.0,13.64,22,08/2024,Occupational Expert
14,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),4.0,13.64,22,08/2024,Occupational Expert
15,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),5.0,13.64,22,08/2024,Occupational Expert
16,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),6.0,13.64,22,08/2024,Occupational Expert
17,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),7.0,0.00,22,08/2024,Occupational Expert
18,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),8.0,4.55,22,08/2024,Occupational Expert
19,15-2051.01,Business Intelligence Analysts,3.A.2,On-Site or In-Plant Training,PT,On-Site Or In-Plant Training (Categories 1-9),9.0,0.00,22,08/2024,Occupational Expert
20,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),1.0,13.64,22,08/2024,Occupational Expert
21,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),2.0,9.09,22,08/2024,Occupational Expert
22,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),3.0,18.18,22,08/2024,Occupational Expert
23,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),4.0,18.18,22,08/2024,Occupational Expert
24,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),5.0,31.82,22,08/2024,Occupational Expert
25,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),6.0,4.55,22,08/2024,Occupational Expert
26,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),7.0,4.55,22,08/2024,Occupational Expert
27,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),8.0,0.00,22,08/2024,Occupational Expert
28,15-2051.01,Business Intelligence Analysts,3.A.3,On-the-Job Training,OJ,On-The-Job Training (Categories 1-9),9.0,0.00,22,08/2024,Occupational Expert
29,15-2051.01,Business Intelligence Analysts,3.A.4.a,Job-related Apprenticeship,IM,Importance,NaN,1.82,22,08/2024,Occupational Expert

In [32]:
# ============================================================
# STAGE 14.2 — STANDARDIZE TRAINING & EXPERIENCE
# ============================================================

import pandas as pd

# Make a copy
training_std = training_master.copy()

# ------------------------------------------------------------
# CLEAN TEXT FIELDS
# ------------------------------------------------------------

text_columns = [
    "O*NET-SOC Code",
    "Title",
    "Element ID",
    "Element Name",
    "Scale ID",
    "Scale Name",
    "Category",
    "Domain Source"
]

for column in text_columns:
    if column in training_std.columns:
        training_std[column] = (
            training_std[column]
            .astype(str)
            .str.strip()
        )

# ------------------------------------------------------------
# CONVERT DATA VALUE TO NUMERIC
# ------------------------------------------------------------

training_std["Data Value"] = pd.to_numeric(
    training_std["Data Value"],
    errors="coerce"
)

# ------------------------------------------------------------
# CREATE STANDARDIZED FIELDS
# ------------------------------------------------------------

training_std["occupation_code"] = target_code

training_std["occupation_title"] = training_std["Title"]

training_std["item_type"] = "training_experience"

training_std["item_id"] = training_std["Element ID"]

training_std["item_name"] = training_std["Category"]

training_std["importance"] = None

training_std["required_level"] = training_std["Data Value"]

training_std["hot_technology"] = None

training_std["in_demand"] = None

training_std["source"] = "O*NET"

# ------------------------------------------------------------
# SELECT STANDARDIZED COLUMNS
# ------------------------------------------------------------

training_final_columns = [
    "occupation_code",
    "occupation_title",
    "item_type",
    "item_id",
    "item_name",
    "importance",
    "required_level",
    "hot_technology",
    "in_demand",
    "source"
]

training_standardized = training_std[
    training_final_columns
].copy()

# Remove duplicates
training_standardized = (
    training_standardized
    .drop_duplicates()
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("STANDARDIZED TRAINING & EXPERIENCE")
print("=" * 60)

print("Records:", len(training_standardized))

display(training_standardized)

STANDARDIZED TRAINING & EXPERIENCE
============================================================
Records: 30

,occupation_code,occupation_title,item_type,item_id,item_name,importance,required_level,hot_technology,in_demand,source
0,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,1.0,None,0.00,None,None,O*NET
1,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,2.0,None,0.00,None,None,O*NET
2,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,3.0,None,0.00,None,None,O*NET
3,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,4.0,None,0.00,None,None,O*NET
4,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,5.0,None,9.09,None,None,O*NET
5,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,6.0,None,13.64,None,None,O*NET
6,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,7.0,None,36.36,None,None,O*NET
7,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,8.0,None,31.82,None,None,O*NET
8,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,9.0,None,9.09,None,None,O*NET
9,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,10.0,None,0.00,None,None,O*NET
10,15-2051.01,Business Intelligence Analysts,training_experience,3.A.1,11.0,None,0.00,None,None,O*NET
11,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,1.0,None,27.27,None,None,O*NET
12,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,2.0,None,13.64,None,None,O*NET
13,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,3.0,None,13.64,None,None,O*NET
14,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,4.0,None,13.64,None,None,O*NET
15,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,5.0,None,13.64,None,None,O*NET
16,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,6.0,None,13.64,None,None,O*NET
17,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,7.0,None,0.00,None,None,O*NET
18,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,8.0,None,4.55,None,None,O*NET
19,15-2051.01,Business Intelligence Analysts,training_experience,3.A.2,9.0,None,0.00,None,None,O*NET
20,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,1.0,None,13.64,None,None,O*NET
21,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,2.0,None,9.09,None,None,O*NET
22,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,3.0,None,18.18,None,None,O*NET
23,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,4.0,None,18.18,None,None,O*NET
24,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,5.0,None,31.82,None,None,O*NET
25,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,6.0,None,4.55,None,None,O*NET
26,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,7.0,None,4.55,None,None,O*NET
27,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,8.0,None,0.00,None,None,O*NET
28,15-2051.01,Business Intelligence Analysts,training_experience,3.A.3,9.0,None,0.00,None,None,O*NET
29,15-2051.01,Business Intelligence Analysts,training_experience,3.A.4.a,nan,None,1.82,None,None,O*NET

In [33]:
# ============================================================
# STAGE 14.3 — SAVE TRAINING & EXPERIENCE
# ============================================================

from pathlib import Path

PROCESSED_DIR = Path(
    "/home/Student/career-intelligence/data/processed"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

training_file = (
    PROCESSED_DIR /
    "business_intelligence_training_experience.csv"
)

training_standardized.to_csv(
    training_file,
    index=False
)

print("TRAINING & EXPERIENCE DATASET SAVED")
print("=" * 60)
print("File:", training_file)
print("Records:", len(training_standardized))
print("File exists:", training_file.exists())

TRAINING & EXPERIENCE DATASET SAVED
============================================================
File: /home/Student/career-intelligence/data/processed/business_intelligence_training_experience.csv
Records: 30
File exists: True